import React, { createContext, useContext, useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useToast } from '@/components/ui/use-toast'
import { supabase } from '@/lib/supabaseClient'
import { getProfileDisplayName } from '@/lib/profileDisplay'
import { isAutoGeneratedUsername } from '@/lib/identity/username'

const AuthContext = createContext()

export const useAuth = () => useContext(AuthContext)

export const AuthProvider = ({ children }) => {
  const [user, setUser] = useState(null)
  const [loading, setLoading] = useState(true)
  const [followedProfessionals, setFollowedProfessionals] = useState([])
  const navigate = useNavigate()
  const { toast } = useToast()

  const normalizeProfileFields = (profileData) => {
    if (!profileData || typeof profileData !== 'object') return profileData
    // Padronizar snake_case do banco para camelCase usado na UI
    if (profileData.cover_image && !profileData.coverImage) {
      return { ...profileData, coverImage: profileData.cover_image }
    }
    return profileData
  }

  const fetchPublicProfile = async (id) => {
    if (!id) return null

    // Preferir schema novo (username). Fallback para schema antigo (name).
    const attempts = [
      'id, username, username_confirmed, can_offer_service, profession, avatar, cover_image, bio, location',
      'id, username, can_offer_service, profession, avatar, cover_image, bio, location',
      'id, username, profession, avatar, cover_image, bio, location',
      'id, name, can_offer_service, profession, avatar, cover_image, bio, location',
      'id, name, profession, avatar, cover_image, bio, location',
    ]

    let lastError = null
    for (const select of attempts) {
      const res = await supabase.from('profiles').select(select).eq('id', id).single()
      if (!res.error) return res.data
      lastError = res.error

      const msg = String(res.error?.message || res.error)
      const isMissingColumn =
        msg.toLowerCase().includes('column') && msg.toLowerCase().includes('does not exist')
      if (!isMissingColumn) break
    }

    if (lastError) throw lastError
    return null
  }

  useEffect(() => {
    let isMounted = true

    // Check active session on mount (com timeout + fallback)
    const loadSession = async () => {
      const timeoutMs = 8000
      try {
        const { data } = await Promise.race([
          supabase.auth.getSession(),
          new Promise((_, reject) =>
            setTimeout(() => reject(new Error('SESSION_TIMEOUT')), timeoutMs)
          ),
        ])

        const sessionUser = data?.session?.user ?? null
        if (!isMounted) return

        if (sessionUser) {
          try {
            const profileData = await fetchPublicProfile(sessionUser.id)
            if (!isMounted) return
            const normalized = normalizeProfileFields(profileData)
            const display = getProfileDisplayName(normalized)

            const merged = { ...sessionUser, ...normalized, name: display, display_name: display }
            setUser(merged)

            const needsUsernameSetup =
              normalized &&
              (normalized.username_confirmed === false ||
                !normalized.username ||
                isAutoGeneratedUsername(normalized.username, sessionUser.id))
            if (needsUsernameSetup) {
              navigate('/me/edit?tab=personal', { replace: true })
              return
            }
          } catch (_err) {
            if (!isMounted) return
            setUser(sessionUser)
          }
        } else {
          setUser(null)
        }
      } catch (err) {
        if (import.meta.env.DEV) {
          console.warn('Falha ao obter sessão (getSession):', err)
        }
        if (isMounted) {
          setUser(null)
        }
      } finally {
        if (isMounted) setLoading(false)
      }
    }

    loadSession()

    // Listen for auth state changes
    const { data: authListener } = supabase.auth.onAuthStateChange(
      async (_event, session) => {
        const sessionUser = session?.user ?? null
        if (_event === 'SIGNED_IN') {
          let mergedUser = sessionUser
          try {
            const profileData = await fetchPublicProfile(sessionUser.id)
            const normalized = normalizeProfileFields(profileData)
            const display = getProfileDisplayName(normalized)
            mergedUser = { ...sessionUser, ...normalized, name: display, display_name: display }
          } catch (err) {
            // ignore
          }
          setUser(mergedUser)
          toast({
            title: 'Login realizado com sucesso!',
            description: 'Bem-vindo de volta ao JOBY.',
          })

          const needsUsernameSetup =
            mergedUser &&
            (mergedUser.username_confirmed === false ||
              !mergedUser.username ||
              isAutoGeneratedUsername(mergedUser.username, sessionUser.id))

          if (needsUsernameSetup) {
            navigate('/me/edit?tab=personal', { replace: true })
          } else {
            navigate('/')
          }
        }
        if (_event === 'SIGNED_OUT') {
          setUser(null)
          toast({
            title: 'Logout realizado',
            description: 'Você saiu da sua conta.',
          })
          navigate('/login')
        }
      }
    )

    // Load followed professionals from localStorage
    const storedFollowed = localStorage.getItem('joby_followed_professionals')
    if (storedFollowed) {
      setFollowedProfessionals(JSON.parse(storedFollowed))
    }

    return () => {
      isMounted = false
      if (
        authListener &&
        typeof authListener.subscription?.unsubscribe === 'function'
      ) {
        authListener.subscription.unsubscribe()
      }
    }
  }, [navigate, toast])

  const isEmailLike = (value) => {
    const v = String(value ?? '').trim()
    if (!v) return false
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)
  }

  const login = async (identifier, password) => {
    const timeoutMs = 12_000
    setLoading(true)
    try {
      const rawIdentifier = String(identifier ?? '').trim()
      if (!rawIdentifier) {
        toast({
          variant: 'destructive',
          title: 'Dados inválidos',
          description: 'Informe seu nickname ou email.',
        })
        return { success: false, error: 'Identifier vazio.', errorType: 'Dados inválidos' }
      }

      const isEmailLogin = isEmailLike(rawIdentifier)
      let emailToUse = rawIdentifier

      if (!isEmailLogin) {
        const normalizedLogin = rawIdentifier.replace(/^@+/, '')
        const { data: resolvedEmail, error: resolveError } = await Promise.race([
          supabase.rpc('resolve_login_email', { p_login: normalizedLogin }),
          new Promise((_, reject) =>
            setTimeout(() => reject(new Error('LOGIN_TIMEOUT')), timeoutMs)
          ),
        ])

        if (resolveError) {
          const msg = String(resolveError?.message || resolveError)
          const missingFn =
            msg.toLowerCase().includes('function') &&
            msg.toLowerCase().includes('resolve_login_email') &&
            msg.toLowerCase().includes('does not exist')

          toast({
            variant: 'destructive',
            title: missingFn ? 'Login por nickname indisponível' : 'Erro no login',
            description: missingFn
              ? 'Atualize o SQL do Supabase (RPC resolve_login_email) ou entre com email.'
              : msg,
          })
          return {
            success: false,
            error: msg,
            errorType: missingFn ? 'Login por nickname indisponível' : 'Erro no login',
          }
        }

        if (!resolvedEmail) {
          toast({
            variant: 'destructive',
            title: 'Não foi possível entrar com nickname',
            description: 'Tente entrar com seu email (e finalize seu nickname no perfil).',
          })
          return {
            success: false,
            error: 'Nickname não confirmado ou não encontrado.',
            errorType: 'Credenciais inválidas',
          }
        }

        emailToUse = resolvedEmail
      }

      const { error, data } = await Promise.race([
        supabase.auth.signInWithPassword({ email: emailToUse, password }),
        new Promise((_, reject) =>
          setTimeout(() => reject(new Error('LOGIN_TIMEOUT')), timeoutMs)
        ),
      ])

      if (error) {
        // Mensagens de erro mais profissionais e específicas
        let errorTitle = 'Erro no login'
        let errorDescription = 'Não foi possível realizar o login.'

        if (error.message.includes('Invalid login credentials')) {
          errorTitle = 'Credenciais inválidas'
          errorDescription =
            isEmailLogin
              ? 'Email ou senha incorretos. Verifique seus dados e tente novamente.'
              : 'Nickname/email ou senha incorretos. Verifique seus dados e tente novamente.'
        } else if (error.message.includes('Email not confirmed')) {
          errorTitle = 'Email não confirmado'
          errorDescription =
            'Por favor, confirme seu email antes de fazer login. Verifique sua caixa de entrada.'
        } else if (error.message.includes('User not found')) {
          errorTitle = 'Conta não encontrada'
          errorDescription =
            'Não existe uma conta com este email. Que tal criar uma conta agora?'
        } else if (error.message.includes('Too many requests')) {
          errorTitle = 'Muitas tentativas'
          errorDescription =
            'Você tentou fazer login muitas vezes. Aguarde alguns minutos e tente novamente.'
        } else if (error.message.includes('Network')) {
          errorTitle = 'Erro de conexão'
          errorDescription =
            'Verifique sua conexão com a internet e tente novamente.'
        } else {
          errorDescription = error.message
        }

        toast({
          variant: 'destructive',
          title: errorTitle,
          description: errorDescription,
        })
        return { success: false, error: error.message, errorType: errorTitle }
      }

      // Deixe o listener (onAuthStateChange) cuidar de setUser/toast/navigate
      if (data?.session?.user) return { success: true }
      return { success: true }
    } catch (err) {
      const rawMsg = err?.message || String(err || '')
      const isTimeout = rawMsg === 'LOGIN_TIMEOUT'
      const isNetwork =
        isTimeout ||
        err?.status === 0 ||
        err?.code === 'ECONNREFUSED' ||
        err?.code === 'ENOTFOUND' ||
        /Failed to fetch|ENOTFOUND|ERR_NAME_NOT_RESOLVED|NetworkError/i.test(
          rawMsg
        )

      toast({
        variant: 'destructive',
        title: isTimeout
          ? 'Tempo esgotado'
          : isNetwork
          ? 'Erro de conexão'
          : 'Erro no login',
        description: isTimeout
          ? 'O login demorou demais para responder. Verifique sua internet e tente novamente.'
          : isNetwork
          ? 'Não foi possível conectar ao servidor. Verifique sua internet, DNS ou bloqueios locais (VPN/Firewall).'
          : rawMsg,
      })
      return {
        success: false,
        error: isTimeout ? 'Tempo esgotado no login.' : rawMsg,
        errorType: isTimeout
          ? 'Tempo esgotado'
          : isNetwork
          ? 'Erro de conexão'
          : 'Erro no login',
      }
    } finally {
      setLoading(false)
    }
  }

  // Accepts name and profession now
  const register = async (name, email, password, profession) => {
    setLoading(true)
    try {
      // Sign up and set user metadata
      const { data, error } = await supabase.auth.signUp({
        email,
        password,
        options: {
          data: { name, profession },
        },
      })

      if (error) {
        console.error('Supabase signUp error:', error)

        // Mensagens de erro específicas e profissionais
        let errorTitle = 'Erro ao criar conta'
        let errorDescription = 'Não foi possível criar sua conta.'

        if (error.message.includes('User already registered')) {
          errorTitle = 'Email já cadastrado'
          errorDescription =
            'Já existe uma conta com este email. Faça login ou use outro email.'
        } else if (error.message.includes('Password should be at least')) {
          errorTitle = 'Senha muito curta'
          errorDescription = 'A senha deve ter no mínimo 6 caracteres.'
        } else if (error.message.includes('invalid email')) {
          errorTitle = 'Email inválido'
          errorDescription = 'Por favor, insira um email válido.'
        } else if (error.message.includes('Network')) {
          errorTitle = 'Erro de conexão'
          errorDescription =
            'Verifique sua conexão com a internet e tente novamente.'
        } else {
          errorDescription = error.message
        }

        toast({
          variant: 'destructive',
          title: errorTitle,
          description: errorDescription,
        })
        setLoading(false)
        return { success: false, message: error.message, errorType: errorTitle }
      }

      // If user returned, create a profile row in the database
      const createdUser = data?.user
      if (createdUser) {
        try {
          const usernamePlaceholder = `user_${String(createdUser.id).replace(/-/g, '').slice(0, 8)}`
          // Prefer schema novo; se não existir ainda, cai no payload antigo.
          try {
            await supabase.from('profiles').upsert({
              id: createdUser.id,
              username: usernamePlaceholder,
              username_normalized: usernamePlaceholder.toLowerCase(),
              full_name: name,
              profession,
              email: createdUser.email,
            })
          } catch (_e) {
            await supabase.from('profiles').upsert({
              id: createdUser.id,
              name,
              profession,
              email: createdUser.email,
            })
          }
        } catch (err) {
          // ignore - we'll still prompt user to check email
          console.warn('Failed to upsert profile after register:', err)
        }
      }

      toast({
        title: 'Conta criada com sucesso!',
        description:
          'Bem-vindo ao JOBY. Verifique seu email para confirmar a conta.',
      })
      setLoading(false)
      return { success: true }
    } catch (err) {
      console.error('Unexpected error during register:', err)
      const rawMsg = err?.message || String(err || '')
      const isNetwork =
        err?.status === 0 ||
        err?.code === 'ECONNREFUSED' ||
        err?.code === 'ENOTFOUND' ||
        /Failed to fetch|ENOTFOUND|ERR_NAME_NOT_RESOLVED|NetworkError/i.test(
          rawMsg
        )
      const friendlyMsg = isNetwork
        ? 'Não foi possível conectar ao servidor. Verifique sua internet, DNS ou bloqueios locais (VPN/Firewall).'
        : rawMsg
      toast({
        variant: 'destructive',
        title: isNetwork ? 'Erro de conexão' : 'Erro no registro',
        description: friendlyMsg,
      })
      setLoading(false)
      return { success: false, message: rawMsg }
    }
  }

  const logout = async () => {
    setLoading(true)
    const { error } = await supabase.auth.signOut()
    if (error) {
      toast({
        variant: 'destructive',
        title: 'Erro no logout',
        description: error.message,
      })
    }
    setLoading(false)
  }

  const followProfessional = (professionalId) => {
    if (!followedProfessionals.includes(professionalId)) {
      const newFollowed = [...followedProfessionals, professionalId]
      setFollowedProfessionals(newFollowed)
      localStorage.setItem(
        'joby_followed_professionals',
        JSON.stringify(newFollowed)
      )
    }
  }

  const unfollowProfessional = (professionalId) => {
    const newFollowed = followedProfessionals.filter(
      (id) => id !== professionalId
    )
    setFollowedProfessionals(newFollowed)
    localStorage.setItem(
      'joby_followed_professionals',
      JSON.stringify(newFollowed)
    )
  }

  const isFollowing = (professionalId) => {
    return followedProfessionals.includes(professionalId)
  }

  const updateUser = async (updatedUserData) => {
    if (!user) return
    const newUserData = { ...user, ...updatedUserData }

    // Update Supabase user metadata
    try {
      await supabase.auth.updateUser({ data: updatedUserData })
    } catch (err) {
      // ignore metadata update errors
    }

    // Upsert into profiles table (normalizar camelCase -> snake_case)
    try {
      const dbPayload = { id: user.id, ...updatedUserData }
      if (
        Object.prototype.hasOwnProperty.call(dbPayload, 'coverImage') &&
        !Object.prototype.hasOwnProperty.call(dbPayload, 'cover_image')
      ) {
        dbPayload.cover_image = dbPayload.coverImage
        delete dbPayload.coverImage
      }
      await supabase
        .from('profiles')
        .upsert(dbPayload)
    } catch (err) {
      // ignore
    }

    setUser(newUserData)
    localStorage.setItem('joby_user', JSON.stringify(newUserData))
    return newUserData
  }

  const value = {
    user,
    loading,
    login,
    register,
    logout,
    isAuthenticated: !!user,
    followProfessional,
    unfollowProfessional,
    isFollowing,
    updateUser,
  }

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>
}
