import React, { createContext, useContext, useState, useEffect } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { useToast } from '@/components/ui/use-toast'
import { supabase, safeGetSession } from '@/lib/supabaseClient'
import { getProfileDisplayName } from '@/lib/profileDisplay'
import { isAutoGeneratedUsername } from '@/lib/identity/username'
import { useNetworkStatus } from '@/hooks/useNetworkStatus'
import { log } from '@/lib/logger'

const AuthContext = createContext()

export const useAuth = () => useContext(AuthContext)

export const AuthProvider = ({ children }) => {
  const [user, setUser] = useState(null)
  const [loading, setLoading] = useState(true)
  const [profileStatus, setProfileStatus] = useState('loading')
  const [followedProfessionals, setFollowedProfessionals] = useState([])
  const [supabaseResetTick, setSupabaseResetTick] = useState(0)
  const navigate = useNavigate()
  const location = useLocation()
  const { toast } = useToast()
  const { isOffline, rateLimitGate } = useNetworkStatus()

  // Keep the latest route without re-subscribing auth listeners on navigation.
  const currentPathRef = React.useRef(location.pathname)
  useEffect(() => {
    currentPathRef.current = location.pathname
  }, [location.pathname])

  const supabaseResetHandledAtRef = React.useRef(0)
  const authEventSeqRef = React.useRef(0)

  useEffect(() => {
    if (typeof window === 'undefined') return
    const onSupabaseReset = (event) => {
      const at = Number(event?.detail?.at || 0) || Date.now()
      if (at <= supabaseResetHandledAtRef.current) return
      supabaseResetHandledAtRef.current = at

      // Re-run the existing mount hydration logic (session + profile + status)
      setSupabaseResetTick((v) => v + 1)
    }

    window.addEventListener('supabase:reset', onSupabaseReset)
    return () => window.removeEventListener('supabase:reset', onSupabaseReset)
  }, [])

  const lastKnownProfileRef = React.useRef(null)

  // Refs to avoid stale closures during long boot awaits.
  const userRef = React.useRef(user)
  useEffect(() => {
    userRef.current = user
  }, [user])

  const profileStatusRef = React.useRef(profileStatus)
  useEffect(() => {
    profileStatusRef.current = profileStatus
  }, [profileStatus])

  const isOfflineRef = React.useRef(isOffline)
  useEffect(() => {
    isOfflineRef.current = isOffline
    if (isOffline && rateLimitGate(4000)) {
      toast({
        title: 'Sem internet',
        description: 'Alguns dados podem estar desatualizados.',
      })
    }
  }, [isOffline, rateLimitGate, toast])

  const setLogoutReason = (reason) => {
    try {
      if (typeof window === 'undefined') return
      sessionStorage.setItem('joby_auth_logout_reason', String(reason || ''))
    } catch {
      // ignore
    }
  }

  const consumeLogoutReason = () => {
    try {
      if (typeof window === 'undefined') return ''
      const reason = sessionStorage.getItem('joby_auth_logout_reason') || ''
      sessionStorage.removeItem('joby_auth_logout_reason')
      return reason
    } catch {
      return ''
    }
  }

  const ensureOwnProfileExists = async (authUser) => {
    if (!authUser?.id) return
    try {
      // Minimal row to satisfy FK constraints. Other fields are nullable/default.
      await supabase.from('profiles').upsert({ id: authUser.id }, { onConflict: 'id' })
    } catch {
      // ignore
    }
  }

  const normalizeProfileFields = (profileData) => {
    if (!profileData || typeof profileData !== 'object') return profileData
    // Padronizar snake_case do banco para camelCase usado na UI
    if (profileData.cover_image && !profileData.coverImage) {
      return { ...profileData, coverImage: profileData.cover_image }
    }
    return profileData
  }

  const navDebugLog = React.useCallback((to, reason) => {
    if (import.meta.env.DEV !== true) return
    const dest = String(to || '')
    if (!dest) return
    // keep noise low: only log auth-related redirects
    if (!dest.startsWith('/me/edit') && !dest.startsWith('/login')) return
    try {
      log.debug('NAV', dest, reason, new Error().stack)
    } catch {
      // ignore
    }
  }, [])

  const navigateWithReason = React.useCallback(
    (to, { reason, ...opts } = {}) => {
      navDebugLog(to, reason)
      navigate(to, opts)
    },
    [navDebugLog, navigate]
  )

  const isNetworkLikeError = React.useCallback(
    (err) => {
      if (!err) return false
      if (isOfflineRef.current) return true
      const name = String(err?.name || '')
      if (name === 'TimeoutError' || name === 'AbortError') return true
      const msg = String(err?.message || err || '')
      return /Failed to fetch|NetworkError|Network request failed|ERR_NAME_NOT_RESOLVED|ENOTFOUND|ECONNREFUSED|timeout/i.test(
        msg
      )
    },
    []
  )

  const emitAuthReady = React.useCallback((userId, nextProfileStatus) => {
    try {
      if (typeof window === 'undefined') return
      window.dispatchEvent(
        new CustomEvent('auth:ready', {
          detail: {
            at: Date.now(),
            userId: userId ?? null,
            profileStatus: nextProfileStatus,
          },
        })
      )
    } catch {
      // ignore
    }
  }, [])

  const needsCompletionFromProfile = React.useCallback((profileData, authUserId) => {
    if (!profileData) return false
    const username = profileData.username
    const confirmed = profileData.username_confirmed
    return (
      confirmed === false ||
      !username ||
      isAutoGeneratedUsername(username, authUserId)
    )
  }, [])

  const persistLastKnownProfile = React.useCallback((profileData, authUserId) => {
    try {
      if (typeof window === 'undefined') return
      if (!profileData || !authUserId) return
      const payload = {
        id: authUserId,
        profile: profileData,
        savedAt: Date.now(),
      }
      window.sessionStorage?.setItem(
        'joby_last_known_profile_v1',
        JSON.stringify(payload)
      )
    } catch {
      // ignore
    }
  }, [])

  const readPersistedLastKnownProfile = React.useCallback((authUserId) => {
    try {
      if (typeof window === 'undefined') return null
      const raw = window.sessionStorage?.getItem('joby_last_known_profile_v1')
      if (!raw) return null
      const parsed = JSON.parse(raw)
      if (!parsed || parsed.id !== authUserId) return null
      const profile = parsed.profile
      if (!profile || typeof profile !== 'object') return null
      return profile
    } catch {
      return null
    }
  }, [])

  const fetchPublicProfile = async (id) => {
    if (!id) return null

    // Preferir schema novo (username). Fallback para schema antigo (name).
    const attempts = [
      'id, username, username_confirmed, can_offer_service, profession, avatar, cover_image, bio, location, address_cep, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_lat, address_lng, address_formatted, created_at, experience_start_year, joby_since_year',
      'id, username, username_confirmed, can_offer_service, profession, avatar, cover_image, bio, location, created_at, experience_start_year, joby_since_year',
      'id, username, username_confirmed, can_offer_service, profession, avatar, cover_image, bio, location, address_cep, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_lat, address_lng, address_formatted, created_at',
      'id, username, username_confirmed, can_offer_service, profession, avatar, cover_image, bio, location, created_at',
      'id, username, can_offer_service, profession, avatar, cover_image, bio, location, created_at, experience_start_year, joby_since_year',
      'id, username, can_offer_service, profession, avatar, cover_image, bio, location, address_cep, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_lat, address_lng, address_formatted, created_at, experience_start_year, joby_since_year',
      'id, username, can_offer_service, profession, avatar, cover_image, bio, location, created_at',
      'id, username, profession, avatar, cover_image, bio, location, created_at, experience_start_year, joby_since_year',
      'id, username, profession, avatar, cover_image, bio, location, address_cep, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_lat, address_lng, address_formatted, created_at, experience_start_year, joby_since_year',
      'id, username, profession, avatar, cover_image, bio, location, created_at',
      'id, name, can_offer_service, profession, avatar, cover_image, bio, location, created_at, experience_start_year, joby_since_year',
      'id, name, can_offer_service, profession, avatar, cover_image, bio, location, address_cep, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_lat, address_lng, address_formatted, created_at, experience_start_year, joby_since_year',
      'id, name, can_offer_service, profession, avatar, cover_image, bio, location, created_at',
      'id, name, profession, avatar, cover_image, bio, location, created_at, experience_start_year, joby_since_year',
      'id, name, profession, avatar, cover_image, bio, location, address_cep, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_lat, address_lng, address_formatted, created_at, experience_start_year, joby_since_year',
      'id, name, profession, avatar, cover_image, bio, location, created_at',
    ]

    let lastError = null
    for (const select of attempts) {
      const res = await supabase.from('profiles').select(select).eq('id', id).single()
      if (!res.error) return res.data
      lastError = res.error

      const msg = String(res.error?.message || res.error)
      const code = String(res.error?.code || '')

      // Além de schema antigo (colunas não existem), em alguns ambientes o role pode não ter GRANT
      // para colunas novas (insufficient_privilege). Nesses casos, tentamos um select menor.
      const isPermissionDenied =
        code === '42501' ||
        msg.toLowerCase().includes('permission denied') ||
        msg.toLowerCase().includes('insufficient privilege') ||
        msg.toLowerCase().includes('forbidden')

      const isMissingColumn =
        msg.toLowerCase().includes('column') && msg.toLowerCase().includes('does not exist')

      if (isMissingColumn || isPermissionDenied) {
        continue
      }

      break
    }

    if (lastError) throw lastError
    return null
  }

  useEffect(() => {
    let isMounted = true

    const clearAuthStorage = () => {
      try {
        const keys = []
        for (let i = 0; i < localStorage.length; i++) {
          const k = localStorage.key(i)
          if (k) keys.push(k)
        }
        for (const k of keys) {
          if (k.startsWith('sb-') && k.endsWith('-auth-token')) {
            localStorage.removeItem(k)
          }
        }
      } catch {
        // ignore
      }
    }

    const isRefreshTokenInvalid = (err) => {
      const msg = String(err?.message || err || '')
      const code = String(err?.code || '')
      return (
        code === 'refresh_token_not_found' ||
        code === 'session_not_found' ||
        msg.toLowerCase().includes('invalid refresh token') ||
        msg.toLowerCase().includes('refresh token not found') ||
        msg.toLowerCase().includes('session_not_found') ||
        msg.toLowerCase().includes('session not found')
      )
    }

    const isNoProfileRow = (err) => {
      const code = String(err?.code || '')
      const msg = String(err?.message || err || '')
      return (
        code === 'PGRST116' ||
        msg.toLowerCase().includes('json object requested') ||
        msg.toLowerCase().includes('multiple (or no) rows returned')
      )
    }

    // Check active session on mount (com timeout + fallback)
    const loadSession = async () => {
      // DEV: reduzir "tempo de coma" do boot (20s -> 10s).
      const timeoutMs = import.meta.env.DEV ? 10_000 : 8000
      let readyUserId = null
      let readyProfileStatus = null

      const isSessionTimeout = (err) => {
        const msg = String(err?.message || err || '')
        return msg === 'SESSION_TIMEOUT' || msg.toLowerCase().includes('session_timeout')
      }

      const isAuthTimeout = (err) => {
        if (isSessionTimeout(err)) return true
        if (err?.isAcquireTimeout === true) return true
        return String(err?.name || '') === 'TimeoutError'
      }

      try {
        // Só entra em loading "forte" quando não existe user em memória.
        if (isMounted && !userRef.current?.id) setProfileStatus('loading')
        const { data, error } = await safeGetSession(timeoutMs)

        if (error && isRefreshTokenInvalid(error)) {
          // Token inválido no storage (muito comum após rebuild/migração).
          // Limpa localmente e força estado deslogado.
          setLogoutReason('invalid_refresh_token')
          clearAuthStorage()
          try {
            await supabase.auth.signOut({ scope: 'local' })
          } catch {
            // ignore
          }
        }

        const sessionUser = data?.session?.user ?? null
        if (!isMounted) return

        if (sessionUser) {
          try {
            const profileData = await fetchPublicProfile(sessionUser.id)
            if (!isMounted) return
            const normalized = normalizeProfileFields(profileData)
            const display = getProfileDisplayName(normalized)

            const merged = { ...sessionUser, ...normalized, name: display, display_name: display }
            setUser(merged)

            lastKnownProfileRef.current = normalized
            persistLastKnownProfile(normalized, sessionUser.id)

            const needsCompletion = needsCompletionFromProfile(normalized, sessionUser.id)
            const nextStatus = needsCompletion ? 'needs_completion' : 'ready'
            setProfileStatus(nextStatus)
            readyUserId = sessionUser.id
            readyProfileStatus = nextStatus
          } catch (_err) {
            // Falha de rede/offline: isso NÃO é perfil incompleto.
            if (isNetworkLikeError(_err)) {
              const nextStatus = 'error_network'
              setProfileStatus(nextStatus)
              const lastKnown =
                (lastKnownProfileRef.current && lastKnownProfileRef.current.id === sessionUser.id
                  ? lastKnownProfileRef.current
                  : null) ||
                readPersistedLastKnownProfile(sessionUser.id)

              setUser((prev) => {
                if (prev?.id === sessionUser.id) return prev
                if (lastKnown) {
                  const display = getProfileDisplayName(lastKnown)
                  return { ...sessionUser, ...lastKnown, name: display, display_name: display }
                }
                return prev || sessionUser
              })
              readyUserId = sessionUser.id
              readyProfileStatus = nextStatus
              return
            }
            // Profile row missing for some legacy users: create and retry once.
            if (isNoProfileRow(_err)) {
              await ensureOwnProfileExists(sessionUser)
              try {
                const profileData = await fetchPublicProfile(sessionUser.id)
                if (!isMounted) return
                const normalized = normalizeProfileFields(profileData)
                const display = getProfileDisplayName(normalized)
                setUser({ ...sessionUser, ...normalized, name: display, display_name: display })

                lastKnownProfileRef.current = normalized
                persistLastKnownProfile(normalized, sessionUser.id)

                const needsCompletion = needsCompletionFromProfile(normalized, sessionUser.id)
                const nextStatus = needsCompletion ? 'needs_completion' : 'ready'
                setProfileStatus(nextStatus)
                readyUserId = sessionUser.id
                readyProfileStatus = nextStatus
              } catch {
                if (!isMounted) return
                setUser((prev) => prev || sessionUser)
                const nextStatus = 'error_other'
                setProfileStatus(nextStatus)
                readyUserId = sessionUser.id
                readyProfileStatus = nextStatus
              }
              return
            }
            if (!isMounted) return
            setUser((prev) => prev || sessionUser)
            const nextStatus = 'error_other'
            setProfileStatus(nextStatus)
            readyUserId = sessionUser.id
            readyProfileStatus = nextStatus
          }
        } else {
          setUser(null)
          const nextStatus = 'ready'
          setProfileStatus(nextStatus)
          readyUserId = null
          readyProfileStatus = nextStatus
        }
      } catch (err) {
        if (isAuthTimeout(err)) {
          // Timeout no boot: sair de loading sem inventar logout; preservar user/status existentes.
          if (isMounted) {
            const existingUser = userRef.current
            const existingStatus = profileStatusRef.current

            if (existingUser?.id) {
              // Mantém status estável se já existir; se estiver "loading", deriva do lastKnownProfile.
              let nextStatus = existingStatus && existingStatus !== 'loading' ? existingStatus : null

              if (!nextStatus) {
                const lastKnown =
                  (lastKnownProfileRef.current && lastKnownProfileRef.current.id === existingUser.id
                    ? lastKnownProfileRef.current
                    : null) ||
                  readPersistedLastKnownProfile(existingUser.id)

                if (lastKnown) {
                  const needsCompletion = needsCompletionFromProfile(lastKnown, existingUser.id)
                  nextStatus = needsCompletion ? 'needs_completion' : 'ready'
                } else {
                  nextStatus = 'ready'
                }
              }

              setProfileStatus(nextStatus)
              readyUserId = existingUser.id
              readyProfileStatus = nextStatus
            } else {
              // Sem user: não há evidência de sessão; apenas destrava o boot.
              setProfileStatus('ready')
              readyUserId = null
              readyProfileStatus = 'ready'
            }
          }
          return
        }

        if (isNetworkLikeError(err)) {
          // Offline/timeout: não derrube user/sessão nem navegue.
          if (import.meta.env.DEV) log.warn('AUTH', 'Falha de rede ao obter sessão (mantendo user):', err)
          if (isMounted && user?.id) setProfileStatus('error_network')
          return
        }
        // Em DEV/HMR pode acontecer timeout transitório (rede/devtools lento).
        // Não devemos limpar user/sessão por isso, senão vira loop de login.
        if (isRefreshTokenInvalid(err)) {
          setLogoutReason('invalid_refresh_token')
          clearAuthStorage()
          try {
            await supabase.auth.signOut({ scope: 'local' })
          } catch {
            // ignore
          }
          // Esse erro é esperado quando existe token antigo no storage (ex.: troca de projeto/env).
          // Não logamos no console para não assustar em DEV.
        }

        if (import.meta.env.DEV && !isRefreshTokenInvalid(err)) {
          log.warn('AUTH', 'Falha ao obter sessão (getSession):', err)
        }

        if (isMounted) {
          setUser(null)
          const nextStatus = 'ready'
          setProfileStatus(nextStatus)
          readyUserId = null
          readyProfileStatus = nextStatus
        }
      } finally {
        if (isMounted && readyProfileStatus && readyProfileStatus !== 'loading') {
          emitAuthReady(readyUserId, readyProfileStatus)
        }
        if (isMounted) setLoading(false)
      }
    }

    loadSession()

    // Listen for auth state changes
    const handleAuthStateChangeAsync = async (_event, session, seq) => {
      try {
        const isStale = () => !isMounted || seq !== authEventSeqRef.current

        const sessionUser = session?.user ?? null

        if (_event === 'SIGNED_IN') {
          if (!sessionUser?.id) return

          let mergedUser = sessionUser
          let didFetchProfile = false
          let readyProfileStatus = 'ready'

          setProfileStatus('loading')

          try {
            const profileData = await fetchPublicProfile(sessionUser.id)
            if (isStale()) return

            const normalized = normalizeProfileFields(profileData)
            const display = getProfileDisplayName(normalized)
            mergedUser = { ...sessionUser, ...normalized, name: display, display_name: display }
            didFetchProfile = true

            lastKnownProfileRef.current = normalized
            persistLastKnownProfile(normalized, sessionUser.id)

            const needsCompletion = needsCompletionFromProfile(normalized, sessionUser.id)
            readyProfileStatus = needsCompletion ? 'needs_completion' : 'ready'
            setProfileStatus(readyProfileStatus)
          } catch (err) {
            if (isNoProfileRow(err)) {
              try {
                await ensureOwnProfileExists(sessionUser)
                if (isStale()) return

                try {
                  const profileData = await fetchPublicProfile(sessionUser.id)
                  if (isStale()) return

                  const normalized = normalizeProfileFields(profileData)
                  const display = getProfileDisplayName(normalized)
                  mergedUser = { ...sessionUser, ...normalized, name: display, display_name: display }
                  didFetchProfile = true

                  lastKnownProfileRef.current = normalized
                  persistLastKnownProfile(normalized, sessionUser.id)

                  const needsCompletion = needsCompletionFromProfile(normalized, sessionUser.id)
                  readyProfileStatus = needsCompletion ? 'needs_completion' : 'ready'
                  setProfileStatus(readyProfileStatus)
                } catch (retryErr) {
                  if (isStale()) return
                  const fallbackStatus = isNetworkLikeError(retryErr) ? 'error_network' : 'error_other'
                  readyProfileStatus = fallbackStatus
                  setProfileStatus(fallbackStatus)
                }
              } catch (ensureErr) {
                if (isStale()) return
                const fallbackStatus = isNetworkLikeError(ensureErr) ? 'error_network' : 'error_other'
                readyProfileStatus = fallbackStatus
                setProfileStatus(fallbackStatus)
              }
            } else if (isNetworkLikeError(err)) {
              readyProfileStatus = 'error_network'
              setProfileStatus(readyProfileStatus)
              const lastKnown =
                (lastKnownProfileRef.current && lastKnownProfileRef.current.id === sessionUser.id
                  ? lastKnownProfileRef.current
                  : null) ||
                readPersistedLastKnownProfile(sessionUser.id)

              if (lastKnown) {
                const display = getProfileDisplayName(lastKnown)
                mergedUser = { ...sessionUser, ...lastKnown, name: display, display_name: display }
              }
            } else if (!didFetchProfile) {
              readyProfileStatus = 'error_other'
              setProfileStatus(readyProfileStatus)
            }
          }

          if (isStale()) return
          setUser(mergedUser)
          emitAuthReady(sessionUser?.id ?? null, readyProfileStatus)

          const pathAtSignIn = String(currentPathRef.current || '')
          const shouldRedirectToHome = pathAtSignIn === '/login' || pathAtSignIn === '/register'

          if (shouldRedirectToHome) {
            toast({
              title: 'Login realizado com sucesso!',
              description: 'Bem-vindo de volta ao JOBY.',
            })
          }

          // Deixe o MainLayout tomar a decisão de onboarding baseado em profileStatus.
          // No WEB: não force / em SIGNED_IN de recuperação/refresh/visibilidade.
          if (shouldRedirectToHome && !isOfflineRef.current) {
            navigateWithReason('/', { reason: 'auth:signed_in' })
          }
        }

        if (_event === 'SIGNED_OUT') {
          const reason = consumeLogoutReason()

          // Quando offline, não trate como logout automático (a menos que seja explícito).
          if (isOfflineRef.current && reason !== 'user_logout') {
            if (import.meta.env.DEV) log.warn('AUTH', 'SIGNED_OUT enquanto offline — mantendo user em memória')
            return
          }

          setUser(null)
          setProfileStatus('ready')
          if (reason === 'session_expired') {
            toast({
              variant: 'destructive',
              title: 'Sessão expirada',
              description: 'Entre novamente para continuar.',
            })
          } else if (reason === 'invalid_refresh_token') {
            toast({
              variant: 'destructive',
              title: 'Sessão inválida',
              description: 'Entre novamente para continuar.',
            })
          } else {
            toast({
              title: 'Logout realizado',
              description: 'Você saiu da sua conta.',
            })
          }
          navigateWithReason('/login', { reason: `auth:signed_out:${reason || 'unknown'}` })
        }
      } catch (err) {
        if (import.meta.env.DEV) log.warn('AUTH', 'onAuthStateChange handler failed:', err)
      }
    }

    const { data: authListener } = supabase.auth.onAuthStateChange((_event, session) => {
      // Only invalidate/sequence events that actually run the heavy mutable flow.
      // Non-processed events (TOKEN_REFRESHED/INITIAL_SESSION/USER_UPDATED/...) must not
      // invalidate a legit in-flight SIGNED_IN handler.
      if (_event !== 'SIGNED_IN' && _event !== 'SIGNED_OUT') return
      authEventSeqRef.current += 1
      const seq = authEventSeqRef.current
      void handleAuthStateChangeAsync(_event, session, seq)
    })

    // Load followed professionals from localStorage
    const storedFollowed = localStorage.getItem('joby_followed_professionals')
    if (storedFollowed) {
      setFollowedProfessionals(JSON.parse(storedFollowed))
    }

    return () => {
      isMounted = false
      if (
        authListener &&
        typeof authListener.subscription?.unsubscribe === 'function'
      ) {
        authListener.subscription.unsubscribe()
      }
    }
  }, [supabaseResetTick, navigateWithReason, toast, isNetworkLikeError, emitAuthReady, needsCompletionFromProfile, persistLastKnownProfile, readPersistedLastKnownProfile])

  const isEmailLike = (value) => {
    const v = String(value ?? '').trim()
    if (!v) return false
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)
  }

  const login = async (identifier, password) => {
    const timeoutMs = 12_000
    setLoading(true)
    try {
      const rawIdentifier = String(identifier ?? '').trim()
      if (!rawIdentifier) {
        toast({
          variant: 'destructive',
          title: 'Dados inválidos',
          description: 'Informe seu nickname ou email.',
        })
        return { success: false, error: 'Identifier vazio.', errorType: 'Dados inválidos' }
      }

      const isEmailLogin = isEmailLike(rawIdentifier)
      let emailToUse = rawIdentifier

      if (!isEmailLogin) {
        const normalizedLogin = rawIdentifier.replace(/^@+/, '')
        const { data: resolvedEmail, error: resolveError } = await Promise.race([
          supabase.rpc('resolve_login_email', { p_login: normalizedLogin }),
          new Promise((_, reject) =>
            setTimeout(() => reject(new Error('LOGIN_TIMEOUT')), timeoutMs)
          ),
        ])

        if (resolveError) {
          const msg = String(resolveError?.message || resolveError)
          const missingFn =
            msg.toLowerCase().includes('function') &&
            msg.toLowerCase().includes('resolve_login_email') &&
            msg.toLowerCase().includes('does not exist')

          toast({
            variant: 'destructive',
            title: missingFn ? 'Login por nickname indisponível' : 'Erro no login',
            description: missingFn
              ? 'Atualize o SQL do Supabase (RPC resolve_login_email) ou entre com email.'
              : msg,
          })
          return {
            success: false,
            error: msg,
            errorType: missingFn ? 'Login por nickname indisponível' : 'Erro no login',
          }
        }

        if (!resolvedEmail) {
          toast({
            variant: 'destructive',
            title: 'Não foi possível entrar com nickname',
            description: 'Tente entrar com seu email (e finalize seu nickname no perfil).',
          })
          return {
            success: false,
            error: 'Nickname não confirmado ou não encontrado.',
            errorType: 'Credenciais inválidas',
          }
        }

        emailToUse = resolvedEmail
      }

      const { error, data } = await Promise.race([
        supabase.auth.signInWithPassword({ email: emailToUse, password }),
        new Promise((_, reject) =>
          setTimeout(() => reject(new Error('LOGIN_TIMEOUT')), timeoutMs)
        ),
      ])

      if (error) {
        // Mensagens de erro mais profissionais e específicas
        let errorTitle = 'Erro no login'
        let errorDescription = 'Não foi possível realizar o login.'

        if (error.message.includes('Invalid login credentials')) {
          errorTitle = 'Credenciais inválidas'
          errorDescription =
            isEmailLogin
              ? 'Email ou senha incorretos. Verifique seus dados e tente novamente.'
              : 'Nickname/email ou senha incorretos. Verifique seus dados e tente novamente.'
        } else if (error.message.includes('Email not confirmed')) {
          errorTitle = 'Email não confirmado'
          errorDescription =
            'Por favor, confirme seu email antes de fazer login. Verifique sua caixa de entrada.'
        } else if (error.message.includes('User not found')) {
          errorTitle = 'Conta não encontrada'
          errorDescription =
            'Não existe uma conta com este email. Que tal criar uma conta agora?'
        } else if (error.message.includes('Too many requests')) {
          errorTitle = 'Muitas tentativas'
          errorDescription =
            'Você tentou fazer login muitas vezes. Aguarde alguns minutos e tente novamente.'
        } else if (error.message.includes('Network')) {
          errorTitle = 'Erro de conexão'
          errorDescription =
            'Verifique sua conexão com a internet e tente novamente.'
        } else {
          errorDescription = error.message
        }

        toast({
          variant: 'destructive',
          title: errorTitle,
          description: errorDescription,
        })
        return { success: false, error: error.message, errorType: errorTitle }
      }

      // Deixe o listener (onAuthStateChange) cuidar de setUser/toast/navigate
      if (data?.session?.user) return { success: true }
      return { success: true }
    } catch (err) {
      const rawMsg = err?.message || String(err || '')
      const isTimeout = rawMsg === 'LOGIN_TIMEOUT'
      const isNetwork =
        isTimeout ||
        err?.status === 0 ||
        err?.code === 'ECONNREFUSED' ||
        err?.code === 'ENOTFOUND' ||
        /Failed to fetch|ENOTFOUND|ERR_NAME_NOT_RESOLVED|NetworkError/i.test(
          rawMsg
        )

      toast({
        variant: 'destructive',
        title: isTimeout
          ? 'Tempo esgotado'
          : isNetwork
          ? 'Erro de conexão'
          : 'Erro no login',
        description: isTimeout
          ? 'O login demorou demais para responder. Verifique sua internet e tente novamente.'
          : isNetwork
          ? 'Não foi possível conectar ao servidor. Verifique sua internet, DNS ou bloqueios locais (VPN/Firewall).'
          : rawMsg,
      })
      return {
        success: false,
        error: isTimeout ? 'Tempo esgotado no login.' : rawMsg,
        errorType: isTimeout
          ? 'Tempo esgotado'
          : isNetwork
          ? 'Erro de conexão'
          : 'Erro no login',
      }
    } finally {
      setLoading(false)
    }
  }

  // Accepts name and profession now
  const register = async (name, email, password, profession) => {
    setLoading(true)
    try {
      // Sign up and set user metadata
      const { data, error } = await supabase.auth.signUp({
        email,
        password,
        options: {
          data: { name, profession },
        },
      })

      if (error) {
        log.error('AUTH', 'Supabase signUp error:', error)

        // Mensagens de erro específicas e profissionais
        let errorTitle = 'Erro ao criar conta'
        let errorDescription = 'Não foi possível criar sua conta.'

        if (error.message.includes('User already registered')) {
          errorTitle = 'Email já cadastrado'
          errorDescription =
            'Já existe uma conta com este email. Faça login ou use outro email.'
        } else if (error.message.includes('Password should be at least')) {
          errorTitle = 'Senha muito curta'
          errorDescription = 'A senha deve ter no mínimo 6 caracteres.'
        } else if (error.message.includes('invalid email')) {
          errorTitle = 'Email inválido'
          errorDescription = 'Por favor, insira um email válido.'
        } else if (error.message.includes('Network')) {
          errorTitle = 'Erro de conexão'
          errorDescription =
            'Verifique sua conexão com a internet e tente novamente.'
        } else {
          errorDescription = error.message
        }

        toast({
          variant: 'destructive',
          title: errorTitle,
          description: errorDescription,
        })
        setLoading(false)
        return { success: false, message: error.message, errorType: errorTitle }
      }

      // If user returned, create a profile row in the database
      const createdUser = data?.user
      if (createdUser) {
        try {
          const usernamePlaceholder = `user_${String(createdUser.id).replace(/-/g, '').slice(0, 8)}`
          // Prefer schema novo; se não existir ainda, cai no payload antigo.
          try {
            await supabase.from('profiles').upsert({
              id: createdUser.id,
              username: usernamePlaceholder,
              username_normalized: usernamePlaceholder.toLowerCase(),
              full_name: name,
              profession,
              email: createdUser.email,
            })
          } catch (_e) {
            await supabase.from('profiles').upsert({
              id: createdUser.id,
              name,
              profession,
              email: createdUser.email,
            })
          }
        } catch (err) {
          // ignore - we'll still prompt user to check email
          log.warn('AUTH', 'Failed to upsert profile after register:', err)
        }
      }

      toast({
        title: 'Conta criada com sucesso!',
        description:
          'Bem-vindo ao JOBY. Verifique seu email para confirmar a conta.',
      })
      setLoading(false)
      return { success: true }
    } catch (err) {
      log.error('AUTH', 'Unexpected error during register:', err)
      const rawMsg = err?.message || String(err || '')
      const isNetwork =
        err?.status === 0 ||
        err?.code === 'ECONNREFUSED' ||
        err?.code === 'ENOTFOUND' ||
        /Failed to fetch|ENOTFOUND|ERR_NAME_NOT_RESOLVED|NetworkError/i.test(
          rawMsg
        )
      const friendlyMsg = isNetwork
        ? 'Não foi possível conectar ao servidor. Verifique sua internet, DNS ou bloqueios locais (VPN/Firewall).'
        : rawMsg
      toast({
        variant: 'destructive',
        title: isNetwork ? 'Erro de conexão' : 'Erro no registro',
        description: friendlyMsg,
      })
      setLoading(false)
      return { success: false, message: rawMsg }
    }
  }

  const logout = async () => {
    setLoading(true)
    setLogoutReason('user_logout')
    const { error } = await supabase.auth.signOut()
    if (error) {
      toast({
        variant: 'destructive',
        title: 'Erro no logout',
        description: error.message,
      })
    }
    setLoading(false)
  }

  const followProfessional = (professionalId) => {
    if (!followedProfessionals.includes(professionalId)) {
      const newFollowed = [...followedProfessionals, professionalId]
      setFollowedProfessionals(newFollowed)
      localStorage.setItem(
        'joby_followed_professionals',
        JSON.stringify(newFollowed)
      )
    }
  }

  const unfollowProfessional = (professionalId) => {
    const newFollowed = followedProfessionals.filter(
      (id) => id !== professionalId
    )
    setFollowedProfessionals(newFollowed)
    localStorage.setItem(
      'joby_followed_professionals',
      JSON.stringify(newFollowed)
    )
  }

  const isFollowing = (professionalId) => {
    return followedProfessionals.includes(professionalId)
  }

  const updateUser = async (updatedUserData) => {
    if (!user) return
    const newUserData = { ...user, ...updatedUserData }

    // Update Supabase user metadata
    try {
      await supabase.auth.updateUser({ data: updatedUserData })
    } catch (err) {
      // ignore metadata update errors
    }

    // Update profiles table (evita exigir INSERT/UPSERT)
    try {
      const dbPayload = { id: user.id, ...updatedUserData }
      if (
        Object.prototype.hasOwnProperty.call(dbPayload, 'coverImage') &&
        !Object.prototype.hasOwnProperty.call(dbPayload, 'cover_image')
      ) {
        dbPayload.cover_image = dbPayload.coverImage
        delete dbPayload.coverImage
      }
      // Remove id do payload do update (id é usado no filtro)
      const { id, ...updatePayload } = dbPayload
      await supabase
        .from('profiles')
        .update(updatePayload)
        .eq('id', id)
    } catch (err) {
      // ignore
    }

    setUser(newUserData)

    // If user updated fields relevant to onboarding, update profileStatus immediately.
    const nextNeedsCompletion = needsCompletionFromProfile(newUserData, user.id)
    setProfileStatus(nextNeedsCompletion ? 'needs_completion' : 'ready')

    lastKnownProfileRef.current = newUserData
    try {
      if (typeof window !== 'undefined') {
        window.sessionStorage?.setItem(
          'joby_last_known_profile_v1',
          JSON.stringify({ id: user.id, profile: newUserData, savedAt: Date.now() })
        )
      }
    } catch {
      // ignore
    }

    localStorage.setItem('joby_user', JSON.stringify(newUserData))
    return newUserData
  }

  const value = {
    user,
    loading,
    profileStatus,
    login,
    register,
    logout,
    isAuthenticated: !!user,
    isOffline,
    followProfessional,
    unfollowProfessional,
    isFollowing,
    updateUser,
  }

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>
}
