import React, { useState, useEffect } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Camera, Upload, X, Plus, Edit2, Trash2, Briefcase, MapPin } from 'lucide-react'
import { useAuth } from '@/contexts/AuthContext'
import { Button } from '@/components/ui/button'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Autocomplete } from '@/components/ui/autocomplete'
import { Tabs, TabsContent } from '@/components/ui/tabs'
import { SwipeTabsList } from '@/components/SwipeTabs'
import { useSwipeTabs } from '@/hooks/useSwipeTabs'
import { TabTransition } from '@/components/TabTransition'
import { Switch } from '@/components/ui/switch'
import { useToast } from '@/components/ui/use-toast'
import { supabase } from '@/lib/supabaseClient'
import ServiceForm from '@/components/ServiceForm'
import { formatPriceUnit } from '@/lib/priceUnit'
import { useResolvedStorageUrl } from '@/lib/storageUrl'
import { normalizeUsername, validateUsername, isAutoGeneratedUsername } from '@/lib/identity/username'
import { digitsOnly, maskCPF, maskCNPJ, validateCPF, validateCNPJ } from '@/lib/identity/cpfCnpj'
import ProfileAddressPicker from '@/components/ProfileAddressPicker'
import PullToRefresh from '@/components/ui/PullToRefresh'
import ErrorState from '@/components/ui/ErrorState'
import { useNetworkStatus } from '@/hooks/useNetworkStatus'
import { log } from '@/lib/logger'
import { optimizeImageFile } from '@/lib/imageOptimize'
import { formatFileSize } from '@/lib/mediaCompression'
import { normalizeImage, NormalizeImageError } from '@/services/imageNormalizeService'
import { createObjectUrlPreview } from '@/lib/filePreviewUrl'

const professions = [
  // SERVIÇOS POR HORA
  'Eletricista',
  'Encanador',
  'Bombeiro Hidráulico',
  'Técnico de Manutenção',
  'Montador de Móveis',
  'Instalador (TV, suporte, cortina, prateleira)',
  'Marceneiro',
  'Serralheiro',
  'Vidraceiro',
  'Diarista',
  'Faxina Residencial',
  'Limpeza Comercial',
  'Passadeira',
  'Organização Residencial',
  'Manicure',
  'Pedicure',
  'Manicure e Pedicure',
  'Designer de Unhas',
  'Cabeleireiro(a)',
  'Barbeiro',
  'Maquiador(a)',
  'Designer de Sobrancelhas',
  'Lash Designer',
  'Depilador(a)',
  'Técnico de Informática',
  'Suporte Técnico',
  'Manutenção de Computador',
  'Manutenção de Celular',
  'Editor de Vídeo',
  'Designer Gráfico',
  // SERVIÇOS POR DIÁRIA
  'Pedreiro',
  'Ajudante de Pedreiro',
  'Servente de Obras',
  'Pintor',
  'Gesseiro',
  'Azulejista',
  'Carpinteiro',
  'Mestre de Obras',
  'Limpeza Pós-Obra',
  'Limpeza de Terreno',
  'Lavagem de Área Externa',
  'Lavagem de Caixa d’Água',
  'Jardineiro',
  'Corte de Grama',
  'Poda de Árvores',
  'Caseiro',
  'Babá',
  'Cuidador(a) de Idosos',
  'Acompanhante',
  // SERVIÇOS POR EVENTO
  'Garçom',
  'Barman',
  'Cozinheiro(a)',
  'Churrasqueiro',
  'Auxiliar de Cozinha',
  'Recepcionista',
  'Segurança de Evento',
  'Animador de Festa',
  'Fotógrafo',
  'Videomaker',
  'Filmagem de Evento',
  'Cobertura de Evento',
  'Maquiagem para Evento',
  'Penteado para Evento',
  'Pacote Noiva',
  // SERVIÇOS COM VALOR FECHADO / POR DEMANDA
  'Carreto',
  'Frete Pequeno',
  'Mudança Residencial',
  'Lavagem de Sofá',
  'Lavagem de Tapete',
  'Estética Automotiva',
  'Polimento Automotivo',
  'Banho e Tosa',
  'Dedetização',
  // CATEGORIA ABERTA
  'Serviços Gerais',
  'Profissional Autônomo',
  'Multisserviços',
  'Outros Serviços',
  'Sem Categoria Definida',
  // EDUCAÇÃO & ENSINO
  'Professor',
  'Professor Particular',
  'Tutor',
  'Educador',
  'Instrutor',
  'Orientador Educacional',
  'Professor de Matemática',
  'Professor de Física',
  'Professor de Química',
  'Professor de Estatística',
  'Professor de Português',
  'Professor de Literatura',
  'Professor de Redação',
  'Professor de História',
  'Professor de Geografia',
  'Professor de Filosofia',
  'Professor de Sociologia',
  'Professor de Biologia',
  'Professor de Ciências',
  'Professor de Inglês',
  'Professor de Espanhol',
  'Professor de Francês',
  'Professor de Alemão',
  'Professor de Italiano',
  'Professor de Libras',
  'Professor de Português para Estrangeiros',
  'Professor de Informática',
  'Professor de Programação',
  'Professor de Excel',
  'Professor de Design Gráfico',
  'Professor de Edição de Vídeo',
  'Professor de Música',
  'Professor de Violão',
  'Professor de Guitarra',
  'Professor de Piano',
  'Professor de Canto',
  'Professor de Teatro',
  'Professor de Dança',
  'Professor de Desenho',
  'Professor de Pintura',
  'Professor de Educação Física',
  'Personal Trainer',
  'Professor de Yoga',
  'Professor de Pilates',
  'Coach Educacional',
  'Mentor Acadêmico',
  'Professor Geral',
  'Educador Geral',
  'Instrutor Geral',
  // CONSTRUÇÃO & MANUTENÇÃO
  'Pedreiro',
  'Ajudante de Pedreiro',
  'Servente de Obras',
  'Mestre de Obras',
  'Eletricista',
  'Eletricista Residencial',
  'Eletricista Industrial',
  'Encanador',
  'Bombeiro Hidráulico',
  'Pintor',
  'Gesseiro',
  'Azulejista',
  'Marceneiro',
  'Carpinteiro',
  'Serralheiro',
  'Soldador',
  'Vidraceiro',
  'Telhadista',
  'Impermeabilizador',
  'Instalador',
  'Técnico em Refrigeração',
  // LIMPEZA & ORGANIZAÇÃO
  'Diarista',
  'Faxineiro',
  'Auxiliar de Limpeza',
  'Governanta',
  'Passadeira',
  'Organizador Profissional',
  // BELEZA & ESTÉTICA
  'Manicure',
  'Pedicure',
  'Nail Designer',
  'Cabeleireiro',
  'Barbeiro',
  'Maquiador',
  'Designer de Sobrancelhas',
  'Lash Designer',
  'Esteticista',
  'Depilador',
  'Massoterapeuta',
  'Micropigmentador',
  // MODA & IMAGEM
  'Costureiro',
  'Alfaiate',
  'Modelista',
  'Consultor de Imagem',
  'Personal Stylist',
  // AUTOMOTIVO
  'Mecânico',
  'Mecânico Automotivo',
  'Eletricista Automotivo',
  'Funileiro',
  'Pintor Automotivo',
  'Esteticista Automotivo',
  'Lavador Automotivo',
  'Guincheiro',
  // TECNOLOGIA & DIGITAL
  'Técnico de Informática',
  'Analista de Suporte',
  'Técnico em Redes',
  'Desenvolvedor',
  'Desenvolvedor Web',
  'Desenvolvedor Mobile',
  'Designer Gráfico',
  'Editor de Vídeo',
  'Social Media',
  'Gestor de Tráfego',
  'Fotógrafo',
  'Videomaker',
  // LOGÍSTICA & TRANSPORTE
  'Motoboy',
  'Entregador',
  'Motorista Particular',
  'Motorista de Aplicativo',
  'Carreteiro',
  'Caminhoneiro',
  'Ajudante de Mudança',
  // EXTERNOS & CAMPO
  'Jardineiro',
  'Paisagista',
  'Caseiro',
  'Tratorista',
  // CUIDADOS & ASSISTÊNCIA
  'Babá',
  'Cuidador de Idosos',
  'Cuidador Infantil',
  'Acompanhante',
  'Enfermeiro',
  'Técnico de Enfermagem',
  // PETS
  'Adestrador de Cães',
  'Cuidador de Pets',
  'Tosador',
  'Banhista',
  // EDUCAÇÃO (RESUMO)
  'Professor',
  'Tutor',
  'Instrutor',
  'Educador',
  'Personal Trainer',
  'Professor de Idiomas',
  'Professor de Música',
  // ALIMENTAÇÃO
  'Cozinheiro',
  'Chef',
  'Auxiliar de Cozinha',
  'Confeiteiro',
  'Padeiro',
  'Churrasqueiro',
  // EVENTOS
  'Garçom',
  'Barman',
  'Recepcionista',
  'Cerimonialista',
  'Animador',
  'DJ',
  'Iluminador',
  'Sonoplasta',
  'Produtor de Eventos',
  // CONSULTORIA & PROFISSIONAIS LIBERAIS
  'Consultor',
  'Assessor',
  'Coach',
  'Mentor',
  'Tradutor',
  'Intérprete',
  // SERVIÇOS GERAIS (ABERTA)
  'Prestador de Serviços',
  'Multisserviços',
  'Autônomo',
  // CATEGORIA NEUTRA
  'Sem Profissão Definida',
  // CASA & APOIO DOMÉSTICO
  'Empregada Doméstica',
  'Copeiro',
  'Mordomo',
  'Zelador',
  'Porteiro',
  // CONDOMÍNIOS & PRÉDIOS
  'Síndico Profissional',
  'Supervisor Predial',
  'Auxiliar de Manutenção Predial',
  // SEGURANÇA
  'Vigilante',
  'Porteiro Noturno',
  'Controlador de Acesso',
  'Segurança Patrimonial',
  // ADMINISTRATIVO & ESCRITÓRIO
  'Assistente Administrativo',
  'Auxiliar Administrativo',
  'Secretário',
  'Secretária Executiva',
  'Recepcionista',
  'Digitador',
  // FINANCEIRO & NEGÓCIOS
  'Contador',
  'Auxiliar Contábil',
  'Analista Financeiro',
  'Consultor Financeiro',
  'Corretor de Imóveis',
  'Corretor de Seguros',
  // JURÍDICO
  'Advogado',
  'Assistente Jurídico',
  'Paralegal',
  // TÉCNICOS & ESPECIALIZADOS
  'Técnico Eletrônico',
  'Técnico Mecânico',
  'Técnico em Automação',
  'Técnico em Segurança do Trabalho',
  'Técnico Ambiental',
  // SAÚDE (NÃO MÉDICO)
  'Fisioterapeuta',
  'Terapeuta Ocupacional',
  'Psicólogo',
  'Nutricionista',
  'Fonoaudiólogo',
  // TERAPIAS & BEM-ESTAR
  'Terapeuta Holístico',
  'Quiropraxista',
  'Acupunturista',
  'Reiki Terapeuta',
  // ESPORTE & PERFORMANCE
  'Preparador Físico',
  'Treinador Esportivo',
  'Instrutor de Artes Marciais',
  'Instrutor de Natação',
  // LABORATORIAL & INDUSTRIAL LEVE
  'Operador de Máquinas',
  'Operador de Empilhadeira',
  'Inspetor de Qualidade',
  // MÍDIA & ENTRETENIMENTO
  'Streamer',
  'Criador de Conteúdo',
  'Narrador',
  'Locutor',
  // INTERNACIONAL / REMOTO
  'Tradutor',
  'Intérprete',
  'Professor Online',
  'Assistente Virtual',
  // CATEGORIAS FINAIS
  'Freelancer',
  'Profissional Liberal',
  'Autônomo Geral',
]

const ProfileEdit = () => {
  const { user, updateUser } = useAuth()
  const navigate = useNavigate()
  const location = useLocation()
  const { toast } = useToast()

  const { isOffline } = useNetworkStatus()

  const [activeTab, setActiveTab] = useState('public')

  const TAB_ORDER = ['public', 'personal']
  const swipeTabs = useSwipeTabs({
    tabs: TAB_ORDER,
    value: activeTab,
    onValueChange: setActiveTab,
  })

  useEffect(() => {
    const tab = new URLSearchParams(location.search).get('tab')
    if (tab === 'personal' || tab === 'public') {
      setActiveTab(tab)
    }
  }, [location.search])

  const [formData, setFormData] = useState({
    bio: '',
    location: '',
    profession: '',
    experienceYears: '',
    areas: '',
    avatar: null,
    coverImage: null,
  })

  const [areasDraft, setAreasDraft] = useState('')
  const [areasAdding, setAreasAdding] = useState(false)

  const parseAreas = (value) =>
    String(value || '')
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)

  const areasList = parseAreas(formData.areas)

  const addArea = (raw) => {
    const next = String(raw || '').trim()
    if (!next) return

    const existing = areasList
    const normalizedNext = next.toLowerCase()
    const has = existing.some((a) => String(a).toLowerCase() === normalizedNext)
    if (has) return

    const joined = [...existing, next].join(', ')
    setFormData((prev) => ({ ...prev, areas: joined }))
  }

  const maskCep = (v) => {
    const d = String(v || '').replace(/\D/g, '').slice(0, 8)
    if (d.length <= 5) return d
    return `${d.slice(0, 5)}-${d.slice(5)}`
  }

  const [address, setAddress] = useState({
    cep: '',
    street: '',
    number: '',
    complement: '',
    neighborhood: '',
    city: '',
    state: '',
    lat: null,
    lng: null,
    formatted: '',
  })

  const [personal, setPersonal] = useState({
    username: '',
    fullName: '',
    birthDate: '',
    isPj: false,
    cpf: '',
    cnpj: '',
  })

  const [usernameStatus, setUsernameStatus] = useState({
    checking: false,
    available: null,
    message: '',
  })

  const [avatarPreview, setAvatarPreview] = useState(null)
  const [coverPreview, setCoverPreview] = useState(null)
  const [avatarOptimizeNote, setAvatarOptimizeNote] = useState('')
  const [coverOptimizeNote, setCoverOptimizeNote] = useState('')
  const [loading, setLoading] = useState(false)
  const [showServiceForm, setShowServiceForm] = useState(false)
  const [services, setServices] = useState([])
  const [editingService, setEditingService] = useState(null)
  const [deleteServiceConfirmOpen, setDeleteServiceConfirmOpen] = useState(false)
  const [deleteServiceConfirmId, setDeleteServiceConfirmId] = useState(null)

  const [accountLoadError, setAccountLoadError] = useState(null)
  const [accountRefreshing, setAccountRefreshing] = useState(false)

  const toFriendlyAccountErrorMessagePtBR = (err) => {
    if (isOffline) return 'Você está sem internet. Conecte-se para atualizar seus dados.'

    const msg = String(err?.message || '')
    const name = String(err?.name || '')

    if (name === 'TimeoutError') {
      return 'Sem conexão ou servidor lento. Tente novamente.'
    }

    if (/failed to fetch|fetch failed|networkerror/i.test(msg)) {
      return 'Sem conexão ou servidor lento. Tente novamente.'
    }

    return msg || 'Não foi possível carregar seus dados agora.'
  }

  const avatarPreviewSrc = useResolvedStorageUrl(avatarPreview)
  const coverPreviewSrc = useResolvedStorageUrl(coverPreview)

  useEffect(() => {
    if (user) {
      const nowYear = new Date().getFullYear()
      const startYearRaw = user?.experience_start_year ?? user?.experienceStartYear
      const startYearNum = Number(startYearRaw)
      const isPlausibleStartYear =
        Number.isFinite(startYearNum) && startYearNum >= 1900 && startYearNum <= nowYear
      const yearsRaw = isPlausibleStartYear ? nowYear - startYearNum : null
      const experienceYears =
        Number.isFinite(yearsRaw) && yearsRaw >= 1 && yearsRaw <= 80 ? String(yearsRaw) : ''

      setFormData({
        bio: user.bio || '',
        location: user.location || '',
        profession: user.profession || '',
        experienceYears,
        areas: user.areas || '',
      })

      // Endereço (se as colunas existirem no schema)
      setAddress((prev) => ({
        ...prev,
        cep: maskCep(user.address_cep || ''),
        street: user.address_street || '',
        number: user.address_number || '',
        complement: user.address_complement || '',
        neighborhood: user.address_neighborhood || '',
        city: user.address_city || '',
        state: user.address_state || '',
        lat: user.address_lat ?? null,
        lng: user.address_lng ?? null,
        formatted: user.address_formatted || '',
      }))

      setAvatarPreview(user.avatar)
      setCoverPreview(user.coverImage || user.cover_image || null)
      setAvatarOptimizeNote('')
      setCoverOptimizeNote('')
      void refetchAccountData()
    }
  }, [user])

  const refetchAccountData = async () => {
    if (!user?.id) return

    setAccountLoadError(null)
    setAccountRefreshing(true)

    try {
      if (isOffline) {
        const offlineErr = new Error('offline')
        offlineErr.name = 'OfflineError'
        throw offlineErr
      }

      const results = await Promise.allSettled([loadUserServices(), loadPrivateProfile()])
      const firstRejected = results.find((r) => r.status === 'rejected')
      if (firstRejected) {
        throw firstRejected.reason
      }
    } catch (e) {
      setAccountLoadError(e)
      if (import.meta.env.DEV) log.warn('PROFILE', 'Falha ao atualizar dados da conta', e)
    } finally {
      setAccountRefreshing(false)
    }
  }

  const loadPrivateProfile = async () => {
    if (!user?.id) return

    try {
      // Prefer: RPC (quando RLS/GRANT restringir colunas privadas)
      const { data, error } = await supabase.rpc('get_my_profile_private')
      if (!error && data) {
        const row = Array.isArray(data) ? data[0] : data
        setPersonal((prev) => ({
          ...prev,
          username: row?.username || user?.username || '',
          fullName: row?.full_name || '',
          birthDate: row?.birth_date || '',
          isPj: !!row?.is_pj,
          cpf: maskCPF(row?.cpf || ''),
          cnpj: maskCNPJ(row?.cnpj || ''),
        }))
        return
      }

      // Fallback: schema ainda antigo (antes de aplicar SQL)
      const res = await supabase
        .from('profiles')
        .select('id, username, full_name, birth_date, cpf, cnpj, is_pj')
        .eq('id', user.id)
        .single()
      if (res.error) throw res.error
      const row = res.data
      setPersonal((prev) => ({
        ...prev,
        username: row?.username || user?.username || '',
        fullName: row?.full_name || '',
        birthDate: row?.birth_date || '',
        isPj: !!row?.is_pj,
        cpf: maskCPF(row?.cpf || ''),
        cnpj: maskCNPJ(row?.cnpj || ''),
      }))
    } catch (e) {
      if (import.meta.env.DEV) log.warn('PROFILE', 'Falha ao carregar dados pessoais', e)
      throw e
    }
  }

  useEffect(() => {
    if (!user?.id) return

    const raw = personal.username
    const v = validateUsername(raw)
    const normalized = v.ok ? v.username : normalizeUsername(raw)
    const current = normalizeUsername(user?.username || '')

    // Se não mudou, não precisa checar
    if (normalized && current && normalized === current) {
      setUsernameStatus({ checking: false, available: true, message: 'Atual' })
      return
    }

    if (!raw) {
      setUsernameStatus({ checking: false, available: null, message: '' })
      return
    }

    if (!v.ok) {
      setUsernameStatus({ checking: false, available: null, message: v.reason })
      return
    }

    let cancelled = false
    setUsernameStatus({ checking: true, available: null, message: 'Verificando…' })

    const t = setTimeout(async () => {
      try {
        const { data, error } = await supabase.rpc('check_username_available', {
          p_username: v.username,
          p_exclude_user_id: user.id,
        })

        if (cancelled) return
        if (error) throw error

        setUsernameStatus({
          checking: false,
          available: !!data,
          message: data ? 'Disponível' : 'Indisponível',
        })
      } catch (e) {
        if (cancelled) return
        setUsernameStatus({ checking: false, available: null, message: 'Não foi possível verificar agora.' })
      }
    }, 400)

    return () => {
      cancelled = true
      clearTimeout(t)
    }
  }, [personal.username, user?.id])

  const loadUserServices = async () => {
    if (!user?.id) return

    try {
      const { data, error } = await supabase
        .from('services')
        .select('*')
        .eq('user_id', user.id)
        .eq('is_active', true)
      if (error) throw error
      setServices(data || [])
    } catch (error) {
      log.error('SERVICE', 'Erro ao carregar serviços', error)
      throw error
    }
  }

  const handleAddService = () => {
    setEditingService(null)
    setShowServiceForm(true)
  }

  const handleEditService = (service) => {
    setEditingService(service)
    setShowServiceForm(true)
  }

  const openDeleteServiceConfirm = (serviceId) => {
    if (!serviceId) return
    setDeleteServiceConfirmId(serviceId)
    setDeleteServiceConfirmOpen(true)
  }

  const handleSaveService = (serviceData) => {
    if (editingService) {
      setServices((prev) =>
        prev.map((s) => (s.id === serviceData.id ? serviceData : s))
      )
      toast({
        title: 'Serviço Atualizado!',
        description: `O serviço "${serviceData.title}" foi atualizado com sucesso.`,
        variant: 'success',
        duration: 3000,
      })
    } else {
      setServices((prev) => [serviceData, ...prev])
      toast({
        title: 'Serviço Adicionado!',
        description: `O serviço "${serviceData.title}" foi criado com sucesso.`,
        variant: 'success',
        duration: 3000,
      })
    }
    setShowServiceForm(false)
    setEditingService(null)
  }

  const handleDeleteService = async (serviceId) => {
    if (!user?.id) {
      toast({
        title: 'Login necessário',
        description: 'Você precisa estar logado para excluir um serviço.',
        variant: 'destructive',
      })
      return
    }
    if (!serviceId) return

    try {
      const { error } = await supabase
        .from('services')
        .update({ is_active: false })
        .eq('id', serviceId)
        .eq('user_id', user.id)

      if (error) throw error

      setServices((prev) => prev.filter((s) => s.id !== serviceId))
      toast({
        title: 'Serviço removido',
        description: 'O serviço foi removido com sucesso.',
        variant: 'success',
        duration: 3000,
      })
    } catch (error) {
      log.error('SERVICE', 'Erro ao excluir serviço', error)
      toast({
        title: 'Erro ao excluir',
        description: error?.message || 'Não foi possível excluir. Tente novamente.',
        variant: 'destructive',
        duration: 3000,
      })
    }
  }

  const handleImageChange = async (e, type) => {
    const file = e.target.files[0]
    if (file) {
      if (type === 'avatar') setAvatarOptimizeNote('')
      else setCoverOptimizeNote('')

      // Preview ASAP before optimization/conversion.
      try {
        const previewUrl = createObjectUrlPreview(file, type === 'avatar' ? avatarPreview : coverPreview)
        if (type === 'avatar') setAvatarPreview(previewUrl)
        else setCoverPreview(previewUrl)
      } catch {
        // ignore
      }

      // Extreme-only block.
      const MAX_IMAGE_INPUT_BYTES = 30 * 1024 * 1024
      if (file.size > MAX_IMAGE_INPUT_BYTES) {
        toast({
          title: 'Imagem muito grande',
          description: 'Envie uma imagem de até 30MB para otimização automática.',
          variant: 'destructive',
        })
        return
      }

      let fileToUse = file
      try {
        const kind = type === 'avatar' ? 'avatar' : 'photo'
        const { file: optimized, meta } = await optimizeImageFile(file, { kind })
        if (optimized?.size && optimized.size > 0) {
          // Always use WEBP output when optimization succeeds.
          fileToUse = optimized
          const note = `Imagem otimizada: ${formatFileSize(meta.originalSize)} → ${formatFileSize(
            meta.newSize
          )}`
          if (type === 'avatar') setAvatarOptimizeNote(note)
          else setCoverOptimizeNote(note)
        }
      } catch (err) {
        const isUnsupportedClient =
          err?.code === 'IMAGE_TYPE_NOT_ALLOWED' || err?.code === 'GIF_NOT_SUPPORTED'

        if (isUnsupportedClient) {
          if (type === 'avatar') setAvatarOptimizeNote('Convertendo no servidor…')
          else setCoverOptimizeNote('Convertendo no servidor…')

          try {
            const context = type === 'avatar' ? 'profile_avatar' : 'profile_cover'
            const normalized = await normalizeImage({ file, context, target: 'webp' })
            const url = normalized?.result?.url
            if (!url || !String(url).startsWith('storage://')) {
              throw new Error('Resposta inválida do servidor ao normalizar imagem.')
            }

            fileToUse = String(url)
            if (type === 'avatar') setAvatarOptimizeNote('Imagem convertida no servidor')
            else setCoverOptimizeNote('Imagem convertida no servidor')
          } catch (e) {
            const status = e instanceof NormalizeImageError ? e.status : 0
            const msg =
              status === 415
                ? 'Esse formato não pode ser convertido no servidor no momento. Tente JPG/PNG/WEBP.'
                : e?.message || 'Não foi possível converter a imagem no servidor.'

            toast({
              title: 'Formato não suportado',
              description: msg,
              variant: 'destructive',
            })
            if (type === 'avatar') setAvatarOptimizeNote('')
            else setCoverOptimizeNote('')
            return
          }
        }

        try {
          if (import.meta.env.DEV) log.warn('UPLOAD', 'profile_image_optimize_failed', err)
        } catch {
          // ignore
        }

        toast({
          title: 'Aviso',
          description: 'Não foi possível otimizar a imagem. Usando o arquivo original.',
          variant: 'default',
        })
      }

      if (type === 'avatar') {
        setFormData((prev) => ({ ...prev, avatar: fileToUse }))
      } else {
        setFormData((prev) => ({ ...prev, coverImage: fileToUse }))
      }
    }
  }

  const uploadImage = async (file, path) => {
    const fileExt = file.name.split('.').pop()
    const fileName = `${path}/${user.id}-${Date.now()}.${fileExt}`
    const { data, error } = await supabase.storage
      .from('profile-photos')
      .upload(fileName, file, { upsert: true, contentType: file?.type || undefined })
    if (error) {
      throw error
    }
    return `storage://profile-photos/${fileName}`
  }

  const handleCameraCapture = async (type) => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true })
      // Aqui você pode implementar a captura de foto da câmera
      // Por enquanto, vamos apenas mostrar um toast
      toast({
        title: 'Câmera não implementada',
        description:
          'A captura de foto pela câmera será implementada em breve.',
      })
    } catch (err) {
      toast({
        title: 'Erro ao acessar câmera',
        description: 'Verifique se você concedeu permissão para usar a câmera.',
        variant: 'destructive',
      })
    }
  }

  const validateForm = () => {
    if (formData.bio && formData.bio.length > 200) {
      toast({
        title: 'Bio muito longa',
        description: 'A bio deve ter no máximo 200 caracteres.',
        variant: 'destructive',
      })
      return false
    }

    // Validar se há contatos na bio
    const contactRegex =
      /([0-9]{8,}|@|\.com|www\.|http|whatsapp|facebook|instagram)/i
    if (contactRegex.test(formData.bio)) {
      toast({
        title: 'Informações de contato não permitidas',
        description: 'Não inclua links, e-mails ou números de telefone na bio.',
        variant: 'destructive',
      })
      return false
    }

    return true
  }

  const validatePersonal = () => {
    const v = validateUsername(personal.username)
    if (!v.ok) {
      toast({
        title: 'Nickname inválido',
        description: v.reason,
        variant: 'destructive',
      })
      return false
    }

    if (usernameStatus.available === false) {
      toast({
        title: 'Nickname indisponível',
        description: 'Escolha outro @username para continuar.',
        variant: 'destructive',
      })
      return false
    }

    if (!String(personal.fullName || '').trim()) {
      toast({
        title: 'Nome completo obrigatório',
        description: 'Esse dado fica visível apenas para você, em Informações pessoais.',
        variant: 'destructive',
      })
      return false
    }

    if (!personal.birthDate) {
      toast({
        title: 'Data de nascimento obrigatória',
        description: 'Informe sua data de nascimento.',
        variant: 'destructive',
      })
      return false
    }

    const d = new Date(`${personal.birthDate}T00:00:00`)
    if (Number.isNaN(d.getTime())) {
      toast({
        title: 'Data inválida',
        description: 'Use o formato YYYY-MM-DD.',
        variant: 'destructive',
      })
      return false
    }
    const today = new Date()
    today.setHours(0, 0, 0, 0)
    if (d > today) {
      toast({
        title: 'Data inválida',
        description: 'A data de nascimento não pode ser no futuro.',
        variant: 'destructive',
      })
      return false
    }

    if (personal.isPj) {
      if (digitsOnly(personal.cnpj)) {
        const cnpjOk = validateCNPJ(personal.cnpj)
        if (!cnpjOk.ok) {
          toast({
            title: 'CNPJ inválido',
            description: cnpjOk.reason,
            variant: 'destructive',
          })
          return false
        }
      }
    } else {
      if (digitsOnly(personal.cpf)) {
        const cpfOk = validateCPF(personal.cpf)
        if (!cpfOk.ok) {
          toast({
            title: 'CPF inválido',
            description: cpfOk.reason,
            variant: 'destructive',
          })
          return false
        }
      }
    }

    return true
  }

  const handleSavePersonal = async () => {
    if (!user?.id) return
    if (!validatePersonal()) return

    setLoading(true)
    try {
      const v = validateUsername(personal.username)
      const username = v.ok ? v.username : normalizeUsername(personal.username)
      const cpfDigits = digitsOnly(personal.cpf)
      const cnpjDigits = digitsOnly(personal.cnpj)

      const payload = {
        username,
        username_normalized: username.toLowerCase(),
        full_name: String(personal.fullName || '').trim(),
        birth_date: personal.birthDate,
        is_pj: !!personal.isPj,
        cpf: personal.isPj ? null : cpfDigits || null,
        cnpj: personal.isPj ? cnpjDigits || null : null,
      }

      // Prefer UPDATE (requires only UPDATE privilege). UPSERT requires INSERT+UPDATE.
      const { error } = await supabase.from('profiles').update(payload).eq('id', user.id)
      if (error) throw error

      // Recarregar campos calculados/servidor (ex: can_offer_service)
      let computed = {}
      try {
        const r = await supabase
          .from('profiles')
          .select('can_offer_service, username_confirmed')
          .eq('id', user.id)
          .single()
        if (!r.error && r.data) computed = r.data
      } catch (_e) {
        // ignore
      }

      await updateUser?.({ username, ...computed })

      toast({
        title: 'Informações pessoais salvas',
        description: 'Seus dados foram atualizados com sucesso.',
      })
    } catch (e) {
      log.error('PROFILE', 'Erro ao salvar informações pessoais', e)
      toast({
        title: 'Erro ao salvar',
        description: e?.message || 'Não foi possível salvar agora. Tente novamente.',
        variant: 'destructive',
      })
    } finally {
      setLoading(false)
    }
  }

  const handleSubmit = async (e) => {
    e.preventDefault()

    if (!validateForm()) return

    setLoading(true)
    try {
      const nowYear = new Date().getFullYear()
      const yearsRaw = String(formData.experienceYears ?? '').trim()
      const yearsNum = yearsRaw ? Number(yearsRaw) : NaN
      const experienceStartYear =
        Number.isFinite(yearsNum) && yearsNum > 0
          ? nowYear - Math.floor(yearsNum)
          : null

      // Upload avatar if changed
      let avatarUrl = user.avatar
      if (typeof formData.avatar === 'string' && String(formData.avatar).startsWith('storage://')) {
        avatarUrl = String(formData.avatar)
      } else if (formData.avatar instanceof File) {
        avatarUrl = await uploadImage(formData.avatar, 'avatars')
        if (import.meta.env.DEV) log.debug('UPLOAD', 'Avatar uploaded', avatarUrl)
      }
      // Upload cover image if changed
      let coverUrl = user.cover_image || user.coverImage
      if (typeof formData.coverImage === 'string' && String(formData.coverImage).startsWith('storage://')) {
        coverUrl = String(formData.coverImage)
      } else if (formData.coverImage instanceof File) {
        coverUrl = await uploadImage(formData.coverImage, 'covers')
        if (import.meta.env.DEV) log.debug('UPLOAD', 'Cover uploaded', coverUrl)
      }

      // Update profile in database
      const computedLocation =
        String(address?.city || '').trim() && String(address?.state || '').trim()
          ? `${String(address.city).trim()}, ${String(address.state).trim()}`
          : formData.location

      const baseUpdate = {
        bio: formData.bio,
        location: computedLocation,
        profession: formData.profession,
        areas: formData.areas,
        avatar: avatarUrl,
        cover_image: coverUrl,
        address_cep: digitsOnly(address.cep) || null,
        address_street: address.street || null,
        address_number: address.number || null,
        address_complement: address.complement || null,
        address_neighborhood: address.neighborhood || null,
        address_city: address.city || null,
        address_state: address.state || null,
        address_lat:
          Number.isFinite(Number(address.lat)) ? Number(address.lat) : null,
        address_lng:
          Number.isFinite(Number(address.lng)) ? Number(address.lng) : null,
        address_formatted: address.formatted || null,
        updated_at: new Date().toISOString(),
      }

      // Tentativa com coluna nova
      let updateError = null
      {
        const { error } = await supabase
          .from('profiles')
          .update({
            ...baseUpdate,
            experience_start_year: experienceStartYear,
          })
          .eq('id', user.id)
        updateError = error
      }

      // Fallback: schema antigo (coluna ainda não existe)
      if (updateError && /experience_start_year/i.test(updateError.message || '')) {
        const { error } = await supabase
          .from('profiles')
          .update(baseUpdate)
          .eq('id', user.id)
        updateError = error
      }

      if (updateError) throw updateError

      // Update local user state
      await updateUser({
        bio: formData.bio,
        location: computedLocation,
        profession: formData.profession,
        experience_start_year: experienceStartYear,
        areas: formData.areas,
        avatar: avatarUrl,
        coverImage: coverUrl,
        address_cep: digitsOnly(address.cep) || null,
        address_street: address.street || null,
        address_number: address.number || null,
        address_complement: address.complement || null,
        address_neighborhood: address.neighborhood || null,
        address_city: address.city || null,
        address_state: address.state || null,
        address_lat:
          Number.isFinite(Number(address.lat)) ? Number(address.lat) : null,
        address_lng:
          Number.isFinite(Number(address.lng)) ? Number(address.lng) : null,
        address_formatted: address.formatted || null,
      })

      toast({
        title: 'Perfil atualizado!',
        description: 'Suas alterações foram salvas com sucesso.',
      })

      navigate(`/profile/${user.id}`)
    } catch (error) {
      log.error('PROFILE', 'Error saving profile', error)
      toast({
        title: 'Erro ao salvar',
        description:
          error.message ||
          'Não foi possível salvar as alterações. Tente novamente.',
        variant: 'destructive',
      })
    } finally {
      setLoading(false)
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="h-full overflow-hidden touch-pan-y"
    >
      <PullToRefresh
        className="h-full overflow-y-auto overscroll-contain"
        onRefresh={refetchAccountData}
        isRefreshing={accountRefreshing}
        threshold={70}
        spinnerText={isOffline ? 'Sem internet…' : 'Atualizando…'}
        {...swipeTabs.containerProps}
      >
        <div className="container max-w-2xl mx-auto p-4 pt-4 pb-20 md:pb-6">
          {isOffline ? (
            <div className="mb-3 rounded-lg border border-border/60 bg-muted/30 px-3 py-2 text-sm text-muted-foreground">
              Sem internet. Alguns dados podem estar desatualizados.
            </div>
          ) : null}

          {accountLoadError ? (
            <div className="mb-4">
              <ErrorState
                title="Não foi possível atualizar seus dados"
                message={toFriendlyAccountErrorMessagePtBR(accountLoadError)}
                onRetry={refetchAccountData}
              />
            </div>
          ) : null}

          <form onSubmit={handleSubmit} className="space-y-8">
            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
              <SwipeTabsList
                tabs={[
                  { value: 'public', label: 'Perfil profissional' },
                  { value: 'personal', label: 'Dados da conta' },
                ]}
                listClassName="grid w-full grid-cols-2"
              />

            <TabsContent value="public" className="space-y-8 mt-6">
              <TabTransition value={activeTab} order={['public', 'personal']}>
        {/* Cover Image */}
        <div className="relative h-48 rounded-xl overflow-hidden bg-accent">
          {coverPreview ? (
            <img
              src={coverPreviewSrc}
              alt="Cover"
              className="w-full h-full object-cover"
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center bg-accent">
              <Upload className="w-8 h-8 text-muted-foreground" />
            </div>
          )}
          <div className="absolute top-4 right-4 flex gap-2">
            <input
              type="file"
              accept="image/*"
              onChange={(e) => handleImageChange(e, 'cover')}
              className="hidden"
              id="cover-upload"
            />
            <label
              htmlFor="cover-upload"
              className="bg-background/80 backdrop-blur-sm hover:bg-background/90 text-foreground p-2 rounded-full cursor-pointer"
            >
              <Upload className="w-5 h-5" />
            </label>
            <button
              type="button"
              onClick={() => handleCameraCapture('cover')}
              className="bg-background/80 backdrop-blur-sm hover:bg-background/90 text-foreground p-2 rounded-full"
            >
              <Camera className="w-5 h-5" />
            </button>
          </div>
        </div>

        {coverOptimizeNote ? (
          <p className="mt-2 text-center text-xs text-muted-foreground">{coverOptimizeNote}</p>
        ) : null}

        {/* Avatar */}
        <div className="relative w-24 h-24 mx-auto -mt-12 rounded-full overflow-hidden border-4 border-background">
          {avatarPreview ? (
            <img
              src={avatarPreviewSrc}
              alt="Avatar"
              className="w-full h-full object-cover"
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center bg-accent">
              <Upload className="w-6 h-6 text-muted-foreground" />
            </div>
          )}
          <div className="absolute inset-0 flex items-center justify-center bg-black/40 opacity-0 hover:opacity-100 transition-opacity">
            <input
              type="file"
              accept="image/*"
              onChange={(e) => handleImageChange(e, 'avatar')}
              className="hidden"
              id="avatar-upload"
            />
            <label
              htmlFor="avatar-upload"
              className="p-1.5 bg-background/80 backdrop-blur-sm hover:bg-background/90 rounded-full cursor-pointer mr-2"
            >
              <Upload className="w-4 h-4" />
            </label>
            <button
              type="button"
              onClick={() => handleCameraCapture('avatar')}
              className="p-1.5 bg-background/80 backdrop-blur-sm hover:bg-background/90 rounded-full"
            >
              <Camera className="w-4 h-4" />
            </button>
          </div>
        </div>

        {avatarOptimizeNote ? (
          <p className="mt-2 text-center text-xs text-muted-foreground">{avatarOptimizeNote}</p>
        ) : null}

        {/* Basic Information */}
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="bio">Descrição / Bio</Label>
            <Textarea
              id="bio"
              value={formData.bio}
              onChange={(e) =>
                setFormData((prev) => ({ ...prev, bio: e.target.value }))
              }
              placeholder="Conte um pouco sobre você e seu trabalho (máx. 200 caracteres)"
              maxLength={200}
              className="resize-none"
              rows={4}
            />
            <p className="text-xs text-muted-foreground text-right">
              {formData.bio?.length || 0}/200
            </p>
          </div>

          <div className="space-y-2">
            <Label>Endereço</Label>
            <ProfileAddressPicker
              value={address}
              onChange={setAddress}
              toast={toast}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="profession">Profissão *</Label>
            <Autocomplete
              id="profession"
              options={professions}
              value={formData.profession}
              onChange={(value) => {
                setFormData((prev) => ({ ...prev, profession: value }))
              }}
              placeholder="Digite para buscar profissão..."
              required
              showOtherOption
              className="bg-background/50"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="experienceYears">Tempo de experiência (opcional)</Label>
            <Input
              id="experienceYears"
              type="number"
              inputMode="numeric"
              min={0}
              max={80}
              value={formData.experienceYears}
              onChange={(e) => {
                const digits = digitsOnly(e.target.value)
                const clamped = digits ? String(Math.min(80, Number(digits))) : ''
                setFormData((prev) => ({ ...prev, experienceYears: clamped }))
              }}
              placeholder="Ex.: 10"
            />
            <p className="text-xs text-muted-foreground">
              Isso aparece como “X anos de experiência” no seu perfil.
            </p>
          </div>

          <div className="space-y-2">
            <Label>Áreas de atuação</Label>

            {/* Mantém compatibilidade com o valor salvo como string (separada por vírgulas) */}
            <input
              type="hidden"
              name="areas"
              value={formData.areas || ''}
              readOnly
            />

            <div className="flex flex-wrap items-center gap-2">
              {areasList.map((area, idx) => (
                <div
                  key={`${area}-${idx}`}
                  className="inline-flex items-center gap-2 rounded-full border border-border bg-background px-3 py-1 text-xs font-medium text-foreground"
                >
                  {idx === 0 ? (
                    <MapPin className="h-3.5 w-3.5 text-muted-foreground" />
                  ) : null}
                  <span className="leading-none">{area}</span>
                </div>
              ))}

              {areasAdding ? (
                <div className="inline-flex items-center gap-1 rounded-full border border-border bg-background px-3 py-1">
                  <Plus className="h-3.5 w-3.5 text-muted-foreground" />
                  <input
                    autoFocus
                    value={areasDraft}
                    onChange={(e) => setAreasDraft(e.target.value)}
                    onBlur={() => {
                      addArea(areasDraft)
                      setAreasDraft('')
                      setAreasAdding(false)
                    }}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') {
                        e.preventDefault()
                        addArea(areasDraft)
                        setAreasDraft('')
                        setAreasAdding(false)
                      }
                      if (e.key === 'Escape') {
                        e.preventDefault()
                        setAreasDraft('')
                        setAreasAdding(false)
                      }
                    }}
                    placeholder="Adicionar"
                    className="h-4 w-28 bg-transparent text-xs outline-none placeholder:text-muted-foreground"
                  />
                </div>
              ) : (
                <button
                  type="button"
                  onClick={() => setAreasAdding(true)}
                  className="inline-flex items-center gap-1 rounded-full border border-border bg-background px-3 py-1 text-xs text-muted-foreground hover:text-foreground"
                >
                  <Plus className="h-3.5 w-3.5" />
                  <span className="max-w-[40px] truncate">Adic</span>
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Serviços */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold">Serviços</h3>
            <Button
              type="button"
              onClick={handleAddService}
              className="joby-gradient text-primary-foreground"
            >
              <Plus className="w-4 h-4 mr-2" />
              Adicionar Serviço
            </Button>
          </div>

          {services.length > 0 ? (
            <div className="space-y-3">
              {services.map((service) => (
                <div
                  key={service.id}
                  className="border border-border rounded-lg p-4 bg-muted/30"
                >
                  <div className="flex justify-between items-start mb-2">
                    <div className="flex-1">
                      <h4 className="font-semibold text-foreground">
                        {service.title}
                      </h4>
                      <p className="text-sm text-primary font-medium">
                        R$ {service.price} / {formatPriceUnit(service.price_unit || service.unit || service.priceUnit)}
                      </p>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        type="button"
                        size="sm"
                        variant="ghost"
                        onClick={() => handleEditService(service)}
                      >
                        <Edit2 className="w-4 h-4" />
                      </Button>
                      <Button
                        type="button"
                        size="sm"
                        variant="ghost"
                        onClick={() => openDeleteServiceConfirm(service.id)}
                        className="text-destructive hover:text-destructive"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                  {service.description && (
                    <p className="text-sm text-muted-foreground line-clamp-2">
                      {service.description}
                    </p>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <div className="border border-dashed border-border rounded-lg p-6 text-center">
              <Briefcase className="w-12 h-12 text-muted-foreground mx-auto mb-3" />
              <p className="text-sm text-muted-foreground">
                Adicione serviços com preços, horários e taxas personalizadas.
              </p>
            </div>
          )}
        </div>

        <div className="flex justify-end">
          <Button
            type="submit"
            disabled={loading}
            className="joby-gradient text-primary-foreground"
          >
            {loading ? 'Salvando…' : 'Salvar perfil'}
          </Button>
        </div>

            </TabTransition>

          </TabsContent>

            <TabsContent value="personal" className="space-y-6 mt-6">
              <TabTransition value={activeTab} order={['public', 'personal']}>
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">Informações pessoais</h2>
              <p className="text-sm text-muted-foreground">
                Seus dados civis não aparecem publicamente. O app mostra sempre seu @nickname.
              </p>
            </div>

            {accountLoadError ? (
              <ErrorState
                title={isOffline ? 'Sem internet' : 'Erro ao carregar seus dados'}
                message={toFriendlyAccountErrorMessagePtBR(accountLoadError)}
                onRetry={refetchAccountData}
              />
            ) : null}

            <div className="space-y-4">
              <div className="space-y-2">
                <Label>Nickname</Label>
                <div className="flex items-center gap-2">
                  <div className="px-3 h-10 rounded-md border border-input bg-background flex items-center text-muted-foreground">
                    @
                  </div>
                  <Input
                    value={personal.username}
                    onChange={(e) =>
                      setPersonal((prev) => ({ ...prev, username: e.target.value }))
                    }
                    placeholder="seu.nickname"
                    autoCapitalize="none"
                    autoCorrect="off"
                    spellCheck={false}
                  />
                </div>
                <p
                  className={
                    'text-xs ' +
                    (usernameStatus.available === true
                      ? 'text-emerald-500'
                      : usernameStatus.available === false
                        ? 'text-destructive'
                        : 'text-muted-foreground')
                  }
                >
                  {usernameStatus.checking
                    ? 'Verificando disponibilidade…'
                    : usernameStatus.message ||
                      'Use 3-30 caracteres: letras, números, ponto e underscore.'}
                </p>
              </div>

              <div className="space-y-2">
                <Label>Nome completo</Label>
                <Input
                  value={personal.fullName}
                  onChange={(e) =>
                    setPersonal((prev) => ({ ...prev, fullName: e.target.value }))
                  }
                  placeholder="Seu nome civil"
                />
              </div>

              <div className="space-y-2">
                <Label>Data de nascimento</Label>
                <Input
                  type="date"
                  value={personal.birthDate}
                  onChange={(e) =>
                    setPersonal((prev) => ({ ...prev, birthDate: e.target.value }))
                  }
                />
              </div>

              <div className="flex items-center justify-between gap-3 p-4 rounded-xl border border-border bg-muted/20">
                <div>
                  <p className="font-medium">Sou PJ / Tenho CNPJ</p>
                  <p className="text-xs text-muted-foreground">
                    Ative para cadastrar CNPJ e ocultar CPF.
                  </p>
                </div>
                <Switch
                  checked={personal.isPj}
                  onCheckedChange={(checked) =>
                    setPersonal((prev) => ({
                      ...prev,
                      isPj: !!checked,
                      cpf: checked ? '' : prev.cpf,
                      cnpj: checked ? prev.cnpj : '',
                    }))
                  }
                />
              </div>

              {!personal.isPj ? (
                <div className="space-y-2">
                  <Label>CPF (opcional)</Label>
                  <Input
                    value={personal.cpf}
                    onChange={(e) =>
                      setPersonal((prev) => ({ ...prev, cpf: maskCPF(e.target.value) }))
                    }
                    placeholder="000.000.000-00"
                    inputMode="numeric"
                  />
                </div>
              ) : (
                <div className="space-y-2">
                  <Label>CNPJ (opcional)</Label>
                  <Input
                    value={personal.cnpj}
                    onChange={(e) =>
                      setPersonal((prev) => ({ ...prev, cnpj: maskCNPJ(e.target.value) }))
                    }
                    placeholder="00.000.000/0000-00"
                    inputMode="numeric"
                  />
                </div>
              )}

              {isAutoGeneratedUsername(personal.username, user?.id) ? (
                <div className="p-4 rounded-xl border border-primary/20 bg-primary/5 text-sm">
                  <p className="font-medium text-foreground">Escolha seu @nickname</p>
                  <p className="text-muted-foreground mt-1">
                    Para ficar com o padrão do JOBY, personalize seu nickname.
                  </p>
                </div>
              ) : null}
            </div>

            <div className="flex justify-end">
              <Button
                type="button"
                disabled={loading}
                onClick={handleSavePersonal}
                className="joby-gradient text-primary-foreground"
              >
                {loading ? 'Salvando…' : 'Salvar informações'}
              </Button>
            </div>

              </TabTransition>
            </TabsContent>
          </Tabs>
        </form>

        {/* Service Form Modal */}
        {showServiceForm && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="w-full max-w-2xl max-h-[90vh] overflow-y-auto"
            >
              <ServiceForm
                isOpen={showServiceForm}
                onClose={() => {
                  setShowServiceForm(false)
                  setEditingService(null)
                }}
                onSave={handleSaveService}
                editingService={editingService}
              />
            </motion.div>
          </div>
        )}

        <AlertDialog
          open={deleteServiceConfirmOpen}
          onOpenChange={(open) => {
            setDeleteServiceConfirmOpen(open)
            if (!open) setDeleteServiceConfirmId(null)
          }}
        >
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Excluir serviço?</AlertDialogTitle>
              <AlertDialogDescription>
                O serviço será removido do seu perfil. Você pode adicioná-lo novamente depois.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Voltar</AlertDialogCancel>
              <AlertDialogAction
                className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                onClick={() => {
                  const serviceId = deleteServiceConfirmId
                  if (!serviceId) return
                  setDeleteServiceConfirmOpen(false)
                  setDeleteServiceConfirmId(null)
                  handleDeleteService(serviceId)
                }}
              >
                Excluir
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
      </PullToRefresh>
    </motion.div>
  )
}

export default ProfileEdit
