import React, { useState, useEffect } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Camera, Upload, X, Plus, Edit2, Trash2, Briefcase } from 'lucide-react'
import { useAuth } from '@/contexts/AuthContext'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Autocomplete } from '@/components/ui/autocomplete'
import { Tabs, TabsContent } from '@/components/ui/tabs'
import { SwipeTabsList } from '@/components/SwipeTabs'
import { useSwipeTabs } from '@/hooks/useSwipeTabs'
import { TabTransition } from '@/components/TabTransition'
import { Switch } from '@/components/ui/switch'
import { useToast } from '@/components/ui/use-toast'
import { supabase } from '@/lib/supabaseClient'
import ServiceForm from '@/components/ServiceForm'
import { formatPriceUnit } from '@/lib/priceUnit'
import { useResolvedStorageUrl } from '@/lib/storageUrl'
import { normalizeUsername, validateUsername, isAutoGeneratedUsername } from '@/lib/identity/username'
import { digitsOnly, maskCPF, maskCNPJ, validateCPF, validateCNPJ } from '@/lib/identity/cpfCnpj'

const professions = [
  // SERVIÇOS POR HORA
  'Eletricista',
  'Encanador',
  'Bombeiro Hidráulico',
  'Técnico de Manutenção',
  'Montador de Móveis',
  'Instalador (TV, suporte, cortina, prateleira)',
  'Marceneiro',
  'Serralheiro',
  'Vidraceiro',
  'Diarista',
  'Faxina Residencial',
  'Limpeza Comercial',
  'Passadeira',
  'Organização Residencial',
  'Manicure',
  'Pedicure',
  'Manicure e Pedicure',
  'Designer de Unhas',
  'Cabeleireiro(a)',
  'Barbeiro',
  'Maquiador(a)',
  'Designer de Sobrancelhas',
  'Lash Designer',
  'Depilador(a)',
  'Técnico de Informática',
  'Suporte Técnico',
  'Manutenção de Computador',
  'Manutenção de Celular',
  'Editor de Vídeo',
  'Designer Gráfico',
  // SERVIÇOS POR DIÁRIA
  'Pedreiro',
  'Ajudante de Pedreiro',
  'Servente de Obras',
  'Pintor',
  'Gesseiro',
  'Azulejista',
  'Carpinteiro',
  'Mestre de Obras',
  'Limpeza Pós-Obra',
  'Limpeza de Terreno',
  'Lavagem de Área Externa',
  'Lavagem de Caixa d’Água',
  'Jardineiro',
  'Corte de Grama',
  'Poda de Árvores',
  'Caseiro',
  'Babá',
  'Cuidador(a) de Idosos',
  'Acompanhante',
  // SERVIÇOS POR EVENTO
  'Garçom',
  'Barman',
  'Cozinheiro(a)',
  'Churrasqueiro',
  'Auxiliar de Cozinha',
  'Recepcionista',
  'Segurança de Evento',
  'Animador de Festa',
  'Fotógrafo',
  'Videomaker',
  'Filmagem de Evento',
  'Cobertura de Evento',
  'Maquiagem para Evento',
  'Penteado para Evento',
  'Pacote Noiva',
  // SERVIÇOS COM VALOR FECHADO / POR DEMANDA
  'Carreto',
  'Frete Pequeno',
  'Mudança Residencial',
  'Lavagem de Sofá',
  'Lavagem de Tapete',
  'Estética Automotiva',
  'Polimento Automotivo',
  'Banho e Tosa',
  'Dedetização',
  // CATEGORIA ABERTA
  'Serviços Gerais',
  'Profissional Autônomo',
  'Multisserviços',
  'Outros Serviços',
  'Sem Categoria Definida',
  // EDUCAÇÃO & ENSINO
  'Professor',
  'Professor Particular',
  'Tutor',
  'Educador',
  'Instrutor',
  'Orientador Educacional',
  'Professor de Matemática',
  'Professor de Física',
  'Professor de Química',
  'Professor de Estatística',
  'Professor de Português',
  'Professor de Literatura',
  'Professor de Redação',
  'Professor de História',
  'Professor de Geografia',
  'Professor de Filosofia',
  'Professor de Sociologia',
  'Professor de Biologia',
  'Professor de Ciências',
  'Professor de Inglês',
  'Professor de Espanhol',
  'Professor de Francês',
  'Professor de Alemão',
  'Professor de Italiano',
  'Professor de Libras',
  'Professor de Português para Estrangeiros',
  'Professor de Informática',
  'Professor de Programação',
  'Professor de Excel',
  'Professor de Design Gráfico',
  'Professor de Edição de Vídeo',
  'Professor de Música',
  'Professor de Violão',
  'Professor de Guitarra',
  'Professor de Piano',
  'Professor de Canto',
  'Professor de Teatro',
  'Professor de Dança',
  'Professor de Desenho',
  'Professor de Pintura',
  'Professor de Educação Física',
  'Personal Trainer',
  'Professor de Yoga',
  'Professor de Pilates',
  'Coach Educacional',
  'Mentor Acadêmico',
  'Professor Geral',
  'Educador Geral',
  'Instrutor Geral',
  // CONSTRUÇÃO & MANUTENÇÃO
  'Pedreiro',
  'Ajudante de Pedreiro',
  'Servente de Obras',
  'Mestre de Obras',
  'Eletricista',
  'Eletricista Residencial',
  'Eletricista Industrial',
  'Encanador',
  'Bombeiro Hidráulico',
  'Pintor',
  'Gesseiro',
  'Azulejista',
  'Marceneiro',
  'Carpinteiro',
  'Serralheiro',
  'Soldador',
  'Vidraceiro',
  'Telhadista',
  'Impermeabilizador',
  'Instalador',
  'Técnico em Refrigeração',
  // LIMPEZA & ORGANIZAÇÃO
  'Diarista',
  'Faxineiro',
  'Auxiliar de Limpeza',
  'Governanta',
  'Passadeira',
  'Organizador Profissional',
  // BELEZA & ESTÉTICA
  'Manicure',
  'Pedicure',
  'Nail Designer',
  'Cabeleireiro',
  'Barbeiro',
  'Maquiador',
  'Designer de Sobrancelhas',
  'Lash Designer',
  'Esteticista',
  'Depilador',
  'Massoterapeuta',
  'Micropigmentador',
  // MODA & IMAGEM
  'Costureiro',
  'Alfaiate',
  'Modelista',
  'Consultor de Imagem',
  'Personal Stylist',
  // AUTOMOTIVO
  'Mecânico',
  'Mecânico Automotivo',
  'Eletricista Automotivo',
  'Funileiro',
  'Pintor Automotivo',
  'Esteticista Automotivo',
  'Lavador Automotivo',
  'Guincheiro',
  // TECNOLOGIA & DIGITAL
  'Técnico de Informática',
  'Analista de Suporte',
  'Técnico em Redes',
  'Desenvolvedor',
  'Desenvolvedor Web',
  'Desenvolvedor Mobile',
  'Designer Gráfico',
  'Editor de Vídeo',
  'Social Media',
  'Gestor de Tráfego',
  'Fotógrafo',
  'Videomaker',
  // LOGÍSTICA & TRANSPORTE
  'Motoboy',
  'Entregador',
  'Motorista Particular',
  'Motorista de Aplicativo',
  'Carreteiro',
  'Caminhoneiro',
  'Ajudante de Mudança',
  // EXTERNOS & CAMPO
  'Jardineiro',
  'Paisagista',
  'Caseiro',
  'Tratorista',
  // CUIDADOS & ASSISTÊNCIA
  'Babá',
  'Cuidador de Idosos',
  'Cuidador Infantil',
  'Acompanhante',
  'Enfermeiro',
  'Técnico de Enfermagem',
  // PETS
  'Adestrador de Cães',
  'Cuidador de Pets',
  'Tosador',
  'Banhista',
  // EDUCAÇÃO (RESUMO)
  'Professor',
  'Tutor',
  'Instrutor',
  'Educador',
  'Personal Trainer',
  'Professor de Idiomas',
  'Professor de Música',
  // ALIMENTAÇÃO
  'Cozinheiro',
  'Chef',
  'Auxiliar de Cozinha',
  'Confeiteiro',
  'Padeiro',
  'Churrasqueiro',
  // EVENTOS
  'Garçom',
  'Barman',
  'Recepcionista',
  'Cerimonialista',
  'Animador',
  'DJ',
  'Iluminador',
  'Sonoplasta',
  'Produtor de Eventos',
  // CONSULTORIA & PROFISSIONAIS LIBERAIS
  'Consultor',
  'Assessor',
  'Coach',
  'Mentor',
  'Tradutor',
  'Intérprete',
  // SERVIÇOS GERAIS (ABERTA)
  'Prestador de Serviços',
  'Multisserviços',
  'Autônomo',
  // CATEGORIA NEUTRA
  'Sem Profissão Definida',
  // CASA & APOIO DOMÉSTICO
  'Empregada Doméstica',
  'Copeiro',
  'Mordomo',
  'Zelador',
  'Porteiro',
  // CONDOMÍNIOS & PRÉDIOS
  'Síndico Profissional',
  'Supervisor Predial',
  'Auxiliar de Manutenção Predial',
  // SEGURANÇA
  'Vigilante',
  'Porteiro Noturno',
  'Controlador de Acesso',
  'Segurança Patrimonial',
  // ADMINISTRATIVO & ESCRITÓRIO
  'Assistente Administrativo',
  'Auxiliar Administrativo',
  'Secretário',
  'Secretária Executiva',
  'Recepcionista',
  'Digitador',
  // FINANCEIRO & NEGÓCIOS
  'Contador',
  'Auxiliar Contábil',
  'Analista Financeiro',
  'Consultor Financeiro',
  'Corretor de Imóveis',
  'Corretor de Seguros',
  // JURÍDICO
  'Advogado',
  'Assistente Jurídico',
  'Paralegal',
  // TÉCNICOS & ESPECIALIZADOS
  'Técnico Eletrônico',
  'Técnico Mecânico',
  'Técnico em Automação',
  'Técnico em Segurança do Trabalho',
  'Técnico Ambiental',
  // SAÚDE (NÃO MÉDICO)
  'Fisioterapeuta',
  'Terapeuta Ocupacional',
  'Psicólogo',
  'Nutricionista',
  'Fonoaudiólogo',
  // TERAPIAS & BEM-ESTAR
  'Terapeuta Holístico',
  'Quiropraxista',
  'Acupunturista',
  'Reiki Terapeuta',
  // ESPORTE & PERFORMANCE
  'Preparador Físico',
  'Treinador Esportivo',
  'Instrutor de Artes Marciais',
  'Instrutor de Natação',
  // LABORATORIAL & INDUSTRIAL LEVE
  'Operador de Máquinas',
  'Operador de Empilhadeira',
  'Inspetor de Qualidade',
  // MÍDIA & ENTRETENIMENTO
  'Streamer',
  'Criador de Conteúdo',
  'Narrador',
  'Locutor',
  // INTERNACIONAL / REMOTO
  'Tradutor',
  'Intérprete',
  'Professor Online',
  'Assistente Virtual',
  // CATEGORIAS FINAIS
  'Freelancer',
  'Profissional Liberal',
  'Autônomo Geral',
]

const ProfileEdit = () => {
  const { user, updateUser } = useAuth()
  const navigate = useNavigate()
  const location = useLocation()
  const { toast } = useToast()

  const [activeTab, setActiveTab] = useState('public')

  const TAB_ORDER = ['public', 'personal']
  const swipeTabs = useSwipeTabs({
    tabs: TAB_ORDER,
    value: activeTab,
    onValueChange: setActiveTab,
  })

  useEffect(() => {
    const tab = new URLSearchParams(location.search).get('tab')
    if (tab === 'personal' || tab === 'public') {
      setActiveTab(tab)
    }
  }, [location.search])

  const [formData, setFormData] = useState({
    bio: '',
    location: '',
    profession: '',
    areas: '',
    avatar: null,
    coverImage: null,
  })

  const [personal, setPersonal] = useState({
    username: '',
    fullName: '',
    birthDate: '',
    isPj: false,
    cpf: '',
    cnpj: '',
  })

  const [usernameStatus, setUsernameStatus] = useState({
    checking: false,
    available: null,
    message: '',
  })

  const [avatarPreview, setAvatarPreview] = useState(null)
  const [coverPreview, setCoverPreview] = useState(null)
  const [loading, setLoading] = useState(false)
  const [showServiceForm, setShowServiceForm] = useState(false)
  const [services, setServices] = useState([])
  const [editingService, setEditingService] = useState(null)

  const avatarPreviewSrc = useResolvedStorageUrl(avatarPreview)
  const coverPreviewSrc = useResolvedStorageUrl(coverPreview)

  useEffect(() => {
    if (user) {
      setFormData({
        bio: user.bio || '',
        location: user.location || '',
        profession: user.profession || '',
        areas: user.areas || '',
      })
      setAvatarPreview(user.avatar)
      setCoverPreview(user.coverImage || user.cover_image || null)
      // Carregar serviços do usuário
      loadUserServices()

      // Carregar dados privados (nome civil, nascimento, docs) via RPC quando disponível
      loadPrivateProfile()
    }
  }, [user])

  const loadPrivateProfile = async () => {
    if (!user?.id) return

    try {
      // Prefer: RPC (quando RLS/GRANT restringir colunas privadas)
      const { data, error } = await supabase.rpc('get_my_profile_private')
      if (!error && data) {
        const row = Array.isArray(data) ? data[0] : data
        setPersonal((prev) => ({
          ...prev,
          username: row?.username || user?.username || '',
          fullName: row?.full_name || '',
          birthDate: row?.birth_date || '',
          isPj: !!row?.is_pj,
          cpf: maskCPF(row?.cpf || ''),
          cnpj: maskCNPJ(row?.cnpj || ''),
        }))
        return
      }

      // Fallback: schema ainda antigo (antes de aplicar SQL)
      const res = await supabase
        .from('profiles')
        .select('id, username, full_name, birth_date, cpf, cnpj, is_pj')
        .eq('id', user.id)
        .single()
      if (res.error) throw res.error
      const row = res.data
      setPersonal((prev) => ({
        ...prev,
        username: row?.username || user?.username || '',
        fullName: row?.full_name || '',
        birthDate: row?.birth_date || '',
        isPj: !!row?.is_pj,
        cpf: maskCPF(row?.cpf || ''),
        cnpj: maskCNPJ(row?.cnpj || ''),
      }))
    } catch (e) {
      // Silencioso: não quebrar edição do perfil público
      if (import.meta.env.DEV) console.warn('Falha ao carregar dados pessoais:', e)
    }
  }

  useEffect(() => {
    if (!user?.id) return

    const raw = personal.username
    const v = validateUsername(raw)
    const normalized = v.ok ? v.username : normalizeUsername(raw)
    const current = normalizeUsername(user?.username || '')

    // Se não mudou, não precisa checar
    if (normalized && current && normalized === current) {
      setUsernameStatus({ checking: false, available: true, message: 'Atual' })
      return
    }

    if (!raw) {
      setUsernameStatus({ checking: false, available: null, message: '' })
      return
    }

    if (!v.ok) {
      setUsernameStatus({ checking: false, available: null, message: v.reason })
      return
    }

    let cancelled = false
    setUsernameStatus({ checking: true, available: null, message: 'Verificando…' })

    const t = setTimeout(async () => {
      try {
        const { data, error } = await supabase.rpc('check_username_available', {
          p_username: v.username,
          p_exclude_user_id: user.id,
        })

        if (cancelled) return
        if (error) throw error

        setUsernameStatus({
          checking: false,
          available: !!data,
          message: data ? 'Disponível' : 'Indisponível',
        })
      } catch (e) {
        if (cancelled) return
        setUsernameStatus({ checking: false, available: null, message: 'Não foi possível verificar agora.' })
      }
    }, 400)

    return () => {
      cancelled = true
      clearTimeout(t)
    }
  }, [personal.username, user?.id])

  const loadUserServices = async () => {
    try {
      const { data, error } = await supabase
        .from('services')
        .select('*')
        .eq('user_id', user.id)
      if (error) throw error
      setServices(data || [])
    } catch (error) {
      console.error('Erro ao carregar serviços:', error)
      setServices([])
    }
  }

  const handleAddService = () => {
    setEditingService(null)
    setShowServiceForm(true)
  }

  const handleEditService = (service) => {
    setEditingService(service)
    setShowServiceForm(true)
  }

  const handleSaveService = (serviceData) => {
    if (editingService) {
      setServices((prev) =>
        prev.map((s) => (s.id === serviceData.id ? serviceData : s))
      )
      toast({
        title: 'Serviço Atualizado!',
        description: `O serviço "${serviceData.title}" foi atualizado com sucesso.`,
        variant: 'success',
        duration: 3000,
      })
    } else {
      setServices((prev) => [serviceData, ...prev])
      toast({
        title: 'Serviço Adicionado!',
        description: `O serviço "${serviceData.title}" foi criado com sucesso.`,
        variant: 'success',
        duration: 3000,
      })
    }
    setShowServiceForm(false)
    setEditingService(null)
  }

  const handleDeleteService = (serviceId) => {
    setServices((prev) => prev.filter((s) => s.id !== serviceId))
    toast({
      title: 'Serviço Removido',
      description: 'O serviço foi removido com sucesso.',
      duration: 3000,
    })
  }

  const handleImageChange = async (e, type) => {
    const file = e.target.files[0]
    if (file) {
      const reader = new FileReader()
      reader.onloadend = () => {
        if (type === 'avatar') {
          setAvatarPreview(reader.result)
          setFormData((prev) => ({ ...prev, avatar: file }))
        } else {
          setCoverPreview(reader.result)
          setFormData((prev) => ({ ...prev, coverImage: file }))
        }
      }
      reader.readAsDataURL(file)
    }
  }

  const uploadImage = async (file, path) => {
    const fileExt = file.name.split('.').pop()
    const fileName = `${path}/${user.id}-${Date.now()}.${fileExt}`
    const { data, error } = await supabase.storage
      .from('profile-photos')
      .upload(fileName, file, { upsert: true })
    if (error) {
      throw error
    }
    return `storage://profile-photos/${fileName}`
  }

  const handleCameraCapture = async (type) => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true })
      // Aqui você pode implementar a captura de foto da câmera
      // Por enquanto, vamos apenas mostrar um toast
      toast({
        title: 'Câmera não implementada',
        description:
          'A captura de foto pela câmera será implementada em breve.',
      })
    } catch (err) {
      toast({
        title: 'Erro ao acessar câmera',
        description: 'Verifique se você concedeu permissão para usar a câmera.',
        variant: 'destructive',
      })
    }
  }

  const validateForm = () => {
    if (formData.bio && formData.bio.length > 200) {
      toast({
        title: 'Bio muito longa',
        description: 'A bio deve ter no máximo 200 caracteres.',
        variant: 'destructive',
      })
      return false
    }

    // Validar se há contatos na bio
    const contactRegex =
      /([0-9]{8,}|@|\.com|www\.|http|whatsapp|facebook|instagram)/i
    if (contactRegex.test(formData.bio)) {
      toast({
        title: 'Informações de contato não permitidas',
        description: 'Não inclua links, e-mails ou números de telefone na bio.',
        variant: 'destructive',
      })
      return false
    }

    return true
  }

  const validatePersonal = () => {
    const v = validateUsername(personal.username)
    if (!v.ok) {
      toast({
        title: 'Nickname inválido',
        description: v.reason,
        variant: 'destructive',
      })
      return false
    }

    if (usernameStatus.available === false) {
      toast({
        title: 'Nickname indisponível',
        description: 'Escolha outro @username para continuar.',
        variant: 'destructive',
      })
      return false
    }

    if (!String(personal.fullName || '').trim()) {
      toast({
        title: 'Nome completo obrigatório',
        description: 'Esse dado fica visível apenas para você, em Informações pessoais.',
        variant: 'destructive',
      })
      return false
    }

    if (!personal.birthDate) {
      toast({
        title: 'Data de nascimento obrigatória',
        description: 'Informe sua data de nascimento.',
        variant: 'destructive',
      })
      return false
    }

    const d = new Date(`${personal.birthDate}T00:00:00`)
    if (Number.isNaN(d.getTime())) {
      toast({
        title: 'Data inválida',
        description: 'Use o formato YYYY-MM-DD.',
        variant: 'destructive',
      })
      return false
    }
    const today = new Date()
    today.setHours(0, 0, 0, 0)
    if (d > today) {
      toast({
        title: 'Data inválida',
        description: 'A data de nascimento não pode ser no futuro.',
        variant: 'destructive',
      })
      return false
    }

    if (personal.isPj) {
      if (digitsOnly(personal.cnpj)) {
        const cnpjOk = validateCNPJ(personal.cnpj)
        if (!cnpjOk.ok) {
          toast({
            title: 'CNPJ inválido',
            description: cnpjOk.reason,
            variant: 'destructive',
          })
          return false
        }
      }
    } else {
      if (digitsOnly(personal.cpf)) {
        const cpfOk = validateCPF(personal.cpf)
        if (!cpfOk.ok) {
          toast({
            title: 'CPF inválido',
            description: cpfOk.reason,
            variant: 'destructive',
          })
          return false
        }
      }
    }

    return true
  }

  const handleSavePersonal = async () => {
    if (!user?.id) return
    if (!validatePersonal()) return

    setLoading(true)
    try {
      const v = validateUsername(personal.username)
      const username = v.ok ? v.username : normalizeUsername(personal.username)
      const cpfDigits = digitsOnly(personal.cpf)
      const cnpjDigits = digitsOnly(personal.cnpj)

      const payload = {
        username,
        username_normalized: username.toLowerCase(),
        full_name: String(personal.fullName || '').trim(),
        birth_date: personal.birthDate,
        is_pj: !!personal.isPj,
        cpf: personal.isPj ? null : cpfDigits || null,
        cnpj: personal.isPj ? cnpjDigits || null : null,
      }

      // Prefer UPDATE (requires only UPDATE privilege). UPSERT requires INSERT+UPDATE.
      const { error } = await supabase.from('profiles').update(payload).eq('id', user.id)
      if (error) throw error

      // Recarregar campos calculados/servidor (ex: can_offer_service)
      let computed = {}
      try {
        const r = await supabase
          .from('profiles')
          .select('can_offer_service, username_confirmed')
          .eq('id', user.id)
          .single()
        if (!r.error && r.data) computed = r.data
      } catch (_e) {
        // ignore
      }

      await updateUser?.({ username, ...computed })

      toast({
        title: 'Informações pessoais salvas',
        description: 'Seus dados foram atualizados com sucesso.',
      })
    } catch (e) {
      console.error('Erro ao salvar informações pessoais:', e)
      toast({
        title: 'Erro ao salvar',
        description: e?.message || 'Não foi possível salvar agora. Tente novamente.',
        variant: 'destructive',
      })
    } finally {
      setLoading(false)
    }
  }

  const handleSubmit = async (e) => {
    e.preventDefault()

    if (!validateForm()) return

    setLoading(true)
    try {
      // Upload avatar if changed
      let avatarUrl = user.avatar
      if (formData.avatar instanceof File) {
        avatarUrl = await uploadImage(formData.avatar, 'avatars')
        if (import.meta.env.DEV) console.log('Avatar uploaded:', avatarUrl)
      }
      // Upload cover image if changed
      let coverUrl = user.cover_image || user.coverImage
      if (formData.coverImage instanceof File) {
        coverUrl = await uploadImage(formData.coverImage, 'covers')
        if (import.meta.env.DEV) console.log('Cover uploaded:', coverUrl)
      }

      // Update profile in database
      const { error: updateError } = await supabase
        .from('profiles')
        .update({
          bio: formData.bio,
          location: formData.location,
          profession: formData.profession,
          areas: formData.areas,
          avatar: avatarUrl,
          cover_image: coverUrl,
          updated_at: new Date().toISOString(),
        })
        .eq('id', user.id)

      if (updateError) throw updateError

      // Update local user state
      await updateUser({
        bio: formData.bio,
        location: formData.location,
        profession: formData.profession,
        areas: formData.areas,
        avatar: avatarUrl,
        coverImage: coverUrl,
      })

      toast({
        title: 'Perfil atualizado!',
        description: 'Suas alterações foram salvas com sucesso.',
      })

      navigate(`/profile/${user.id}`)
    } catch (error) {
      console.error('Error saving profile:', error)
      toast({
        title: 'Erro ao salvar',
        description:
          error.message ||
          'Não foi possível salvar as alterações. Tente novamente.',
        variant: 'destructive',
      })
    } finally {
      setLoading(false)
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="container max-w-2xl mx-auto p-4 pt-4 pb-20 md:pb-6 touch-pan-y"
      {...swipeTabs.containerProps}
    >
      <form onSubmit={handleSubmit} className="space-y-8">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <SwipeTabsList
            tabs={[
              { value: 'public', label: 'Perfil profissional' },
              { value: 'personal', label: 'Dados da conta' },
            ]}
            listClassName="grid w-full grid-cols-2"
          />

          <TabsContent value="public" className="space-y-8 mt-6">
            <TabTransition value={activeTab} order={['public', 'personal']}>
        {/* Cover Image */}
        <div className="relative h-48 rounded-xl overflow-hidden bg-accent">
          {coverPreview ? (
            <img
              src={coverPreviewSrc}
              alt="Cover"
              className="w-full h-full object-cover"
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center bg-accent">
              <Upload className="w-8 h-8 text-muted-foreground" />
            </div>
          )}
          <div className="absolute top-4 right-4 flex gap-2">
            <input
              type="file"
              accept="image/*"
              onChange={(e) => handleImageChange(e, 'cover')}
              className="hidden"
              id="cover-upload"
            />
            <label
              htmlFor="cover-upload"
              className="bg-background/80 backdrop-blur-sm hover:bg-background/90 text-foreground p-2 rounded-full cursor-pointer"
            >
              <Upload className="w-5 h-5" />
            </label>
            <button
              type="button"
              onClick={() => handleCameraCapture('cover')}
              className="bg-background/80 backdrop-blur-sm hover:bg-background/90 text-foreground p-2 rounded-full"
            >
              <Camera className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Avatar */}
        <div className="relative w-24 h-24 mx-auto -mt-12 rounded-full overflow-hidden border-4 border-background">
          {avatarPreview ? (
            <img
              src={avatarPreviewSrc}
              alt="Avatar"
              className="w-full h-full object-cover"
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center bg-accent">
              <Upload className="w-6 h-6 text-muted-foreground" />
            </div>
          )}
          <div className="absolute inset-0 flex items-center justify-center bg-black/40 opacity-0 hover:opacity-100 transition-opacity">
            <input
              type="file"
              accept="image/*"
              onChange={(e) => handleImageChange(e, 'avatar')}
              className="hidden"
              id="avatar-upload"
            />
            <label
              htmlFor="avatar-upload"
              className="p-1.5 bg-background/80 backdrop-blur-sm hover:bg-background/90 rounded-full cursor-pointer mr-2"
            >
              <Upload className="w-4 h-4" />
            </label>
            <button
              type="button"
              onClick={() => handleCameraCapture('avatar')}
              className="p-1.5 bg-background/80 backdrop-blur-sm hover:bg-background/90 rounded-full"
            >
              <Camera className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Basic Information */}
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="bio">Descrição / Bio</Label>
            <Textarea
              id="bio"
              value={formData.bio}
              onChange={(e) =>
                setFormData((prev) => ({ ...prev, bio: e.target.value }))
              }
              placeholder="Conte um pouco sobre você e seu trabalho (máx. 200 caracteres)"
              maxLength={200}
              className="resize-none"
              rows={4}
            />
            <p className="text-xs text-muted-foreground text-right">
              {formData.bio?.length || 0}/200
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="location">Localização</Label>
            <Input
              id="location"
              value={formData.location}
              onChange={(e) =>
                setFormData((prev) => ({ ...prev, location: e.target.value }))
              }
              placeholder="Cidade, Estado"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="profession">Profissão *</Label>
            <Autocomplete
              id="profession"
              options={professions}
              value={formData.profession}
              onChange={(value) => {
                setFormData((prev) => ({ ...prev, profession: value }))
              }}
              placeholder="Digite para buscar profissão..."
              required
              showOtherOption
              className="bg-background/50"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="areas">Áreas de atuação</Label>
            <Input
              id="areas"
              value={formData.areas}
              onChange={(e) =>
                setFormData((prev) => ({ ...prev, areas: e.target.value }))
              }
              placeholder="Ex: Zona Sul, Centro, Região Metropolitana"
            />
          </div>
        </div>

        {/* Serviços */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold">Serviços</h3>
            <Button
              type="button"
              onClick={handleAddService}
              className="joby-gradient text-primary-foreground"
            >
              <Plus className="w-4 h-4 mr-2" />
              Adicionar Serviço
            </Button>
          </div>

          {services.length > 0 ? (
            <div className="space-y-3">
              {services.map((service) => (
                <div
                  key={service.id}
                  className="border border-border rounded-lg p-4 bg-muted/30"
                >
                  <div className="flex justify-between items-start mb-2">
                    <div className="flex-1">
                      <h4 className="font-semibold text-foreground">
                        {service.title}
                      </h4>
                      <p className="text-sm text-primary font-medium">
                        R$ {service.price} / {formatPriceUnit(service.unit || service.priceUnit)}
                      </p>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        type="button"
                        size="sm"
                        variant="ghost"
                        onClick={() => handleEditService(service)}
                      >
                        <Edit2 className="w-4 h-4" />
                      </Button>
                      <Button
                        type="button"
                        size="sm"
                        variant="ghost"
                        onClick={() => handleDeleteService(service.id)}
                        className="text-destructive hover:text-destructive"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                  {service.description && (
                    <p className="text-sm text-muted-foreground line-clamp-2">
                      {service.description}
                    </p>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <div className="border border-dashed border-border rounded-lg p-6 text-center">
              <Briefcase className="w-12 h-12 text-muted-foreground mx-auto mb-3" />
              <p className="text-sm text-muted-foreground">
                Adicione serviços com preços, horários e taxas personalizadas.
              </p>
            </div>
          )}
        </div>

        <div className="flex justify-end">
          <Button
            type="submit"
            disabled={loading}
            className="joby-gradient text-primary-foreground"
          >
            {loading ? 'Salvando…' : 'Salvar perfil'}
          </Button>
        </div>

            </TabTransition>

          </TabsContent>

          <TabsContent value="personal" className="space-y-6 mt-6">
            <TabTransition value={activeTab} order={['public', 'personal']}>
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">Informações pessoais</h2>
              <p className="text-sm text-muted-foreground">
                Seus dados civis não aparecem publicamente. O app mostra sempre seu @nickname.
              </p>
            </div>

            <div className="space-y-4">
              <div className="space-y-2">
                <Label>Nickname</Label>
                <div className="flex items-center gap-2">
                  <div className="px-3 h-10 rounded-md border border-input bg-background flex items-center text-muted-foreground">
                    @
                  </div>
                  <Input
                    value={personal.username}
                    onChange={(e) =>
                      setPersonal((prev) => ({ ...prev, username: e.target.value }))
                    }
                    placeholder="seu.nickname"
                    autoCapitalize="none"
                    autoCorrect="off"
                    spellCheck={false}
                  />
                </div>
                <p
                  className={
                    'text-xs ' +
                    (usernameStatus.available === true
                      ? 'text-emerald-500'
                      : usernameStatus.available === false
                        ? 'text-destructive'
                        : 'text-muted-foreground')
                  }
                >
                  {usernameStatus.checking
                    ? 'Verificando disponibilidade…'
                    : usernameStatus.message ||
                      'Use 3-30 caracteres: letras, números, ponto e underscore.'}
                </p>
              </div>

              <div className="space-y-2">
                <Label>Nome completo</Label>
                <Input
                  value={personal.fullName}
                  onChange={(e) =>
                    setPersonal((prev) => ({ ...prev, fullName: e.target.value }))
                  }
                  placeholder="Seu nome civil"
                />
              </div>

              <div className="space-y-2">
                <Label>Data de nascimento</Label>
                <Input
                  type="date"
                  value={personal.birthDate}
                  onChange={(e) =>
                    setPersonal((prev) => ({ ...prev, birthDate: e.target.value }))
                  }
                />
              </div>

              <div className="flex items-center justify-between gap-3 p-4 rounded-xl border border-border bg-muted/20">
                <div>
                  <p className="font-medium">Sou PJ / Tenho CNPJ</p>
                  <p className="text-xs text-muted-foreground">
                    Ative para cadastrar CNPJ e ocultar CPF.
                  </p>
                </div>
                <Switch
                  checked={personal.isPj}
                  onCheckedChange={(checked) =>
                    setPersonal((prev) => ({
                      ...prev,
                      isPj: !!checked,
                      cpf: checked ? '' : prev.cpf,
                      cnpj: checked ? prev.cnpj : '',
                    }))
                  }
                />
              </div>

              {!personal.isPj ? (
                <div className="space-y-2">
                  <Label>CPF (opcional)</Label>
                  <Input
                    value={personal.cpf}
                    onChange={(e) =>
                      setPersonal((prev) => ({ ...prev, cpf: maskCPF(e.target.value) }))
                    }
                    placeholder="000.000.000-00"
                    inputMode="numeric"
                  />
                </div>
              ) : (
                <div className="space-y-2">
                  <Label>CNPJ (opcional)</Label>
                  <Input
                    value={personal.cnpj}
                    onChange={(e) =>
                      setPersonal((prev) => ({ ...prev, cnpj: maskCNPJ(e.target.value) }))
                    }
                    placeholder="00.000.000/0000-00"
                    inputMode="numeric"
                  />
                </div>
              )}

              {isAutoGeneratedUsername(personal.username, user?.id) ? (
                <div className="p-4 rounded-xl border border-primary/20 bg-primary/5 text-sm">
                  <p className="font-medium text-foreground">Escolha seu @nickname</p>
                  <p className="text-muted-foreground mt-1">
                    Para ficar com o padrão do JOBY, personalize seu nickname.
                  </p>
                </div>
              ) : null}
            </div>

            <div className="flex justify-end">
              <Button
                type="button"
                disabled={loading}
                onClick={handleSavePersonal}
                className="joby-gradient text-primary-foreground"
              >
                {loading ? 'Salvando…' : 'Salvar informações'}
              </Button>
            </div>

            </TabTransition>
          </TabsContent>
        </Tabs>
      </form>

      {/* Service Form Modal */}
      {showServiceForm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className="w-full max-w-2xl max-h-[90vh] overflow-y-auto"
          >
            <ServiceForm
              isOpen={showServiceForm}
              onClose={() => {
                setShowServiceForm(false)
                setEditingService(null)
              }}
              onSave={handleSaveService}
              editingService={editingService}
            />
          </motion.div>
        </div>
      )}
    </motion.div>
  )
}

export default ProfileEdit
