export const normalizeUsername = (value) => {
  const raw = String(value ?? '')
  const normalized = raw.trim().toLowerCase()
  // Remove espaços internos
  return normalized.replace(/\s+/g, '')
}

export const validateUsername = (value) => {
  const username = normalizeUsername(value)

  if (!username) return { ok: false, reason: 'Informe um nickname.' }
  if (username.length < 3 || username.length > 30) {
    return { ok: false, reason: 'Use entre 3 e 30 caracteres.' }
  }
  if (!/^[a-z0-9._]+$/.test(username)) {
    return {
      ok: false,
      reason: 'Use apenas letras, números, ponto e underscore.',
    }
  }
  if (username.startsWith('.') || username.endsWith('.')) {
    return { ok: false, reason: 'Não pode começar ou terminar com ponto.' }
  }
  if (username.includes('..')) {
    return { ok: false, reason: 'Não pode ter dois pontos seguidos.' }
  }

  return { ok: true, username }
}

export const isAutoGeneratedUsername = (username, userId) => {
  const u = normalizeUsername(username)
  if (!u) return true
  const id = String(userId || '').replace(/-/g, '').toLowerCase()
  if (!id) return false
  const suffix = id.slice(0, 8)
  return u === `user_${suffix}` || u === `joby_${suffix}`
}
