import React, { useEffect } from 'react'
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import { motion } from 'framer-motion'
import Navigation from '@/components/Navigation'
import { useAuth } from '@/contexts/AuthContext'
import { isAutoGeneratedUsername } from '@/lib/identity/username'

const MainLayout = () => {
  const { isAuthenticated, loading, user } = useAuth()
  const navigate = useNavigate()
  const location = useLocation()

  // Páginas que precisam de largura total
  const fullWidthPages = ['/messages']
  const isFullWidth = fullWidthPages.includes(location.pathname)

  useEffect(() => {
    const publicPaths = ['/termos', '/terms']
    if (
      !loading &&
      !isAuthenticated &&
      !publicPaths.includes(location.pathname)
    ) {
      navigate('/login')
    }
  }, [isAuthenticated, loading, navigate, location.pathname])

  useEffect(() => {
    if (loading) return
    if (!isAuthenticated || !user) return

    const needsUsernameSetup =
      user.username_confirmed === false ||
      !user.username ||
      isAutoGeneratedUsername(user.username, user.id)

    if (needsUsernameSetup && location.pathname !== '/me/edit') {
      navigate('/me/edit?tab=personal', { replace: true })
    }
  }, [isAuthenticated, loading, user, navigate, location.pathname])

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <motion.div
          animate={{
            rotate: 360,
            scale: [1, 1.2, 1],
          }}
          transition={{
            repeat: Infinity,
            duration: 2,
            ease: 'easeInOut',
          }}
          className="w-12 h-12 rounded-full profile-gradient"
        />
      </div>
    )
  }

  return (
    <div className="flex min-h-[100dvh] bg-background">
      <Navigation />

      <main
        className={`flex-1 min-w-0 md:ml-64 ${
          isFullWidth ? 'h-[100dvh] overflow-hidden' : ''
        }`}
      >
        <div
          className={
            isFullWidth
              ? 'h-full flex flex-col overflow-hidden pt-12 pb-0 md:pt-8 md:pb-8 px-0 md:px-4'
              : 'min-h-screen container max-w-3xl mx-auto pt-12 pb-20 md:py-8 px-4'
          }
        >
          <Outlet />
        </div>
      </main>
    </div>
  )
}

export default MainLayout
